<!--NAVIGATION-->
< [Biological Computing in R](06-R.ipynb) | [Main Contents](Index.ipynb) | [Data management, exploration, and visualization](08-Data_R.ipynb) >

# Biological Computing in Python II  <span class="tocSkip"> <a name="chap:python_II"></a>
    
>> ...some things in life are bad. They can really make you mad. Other things just make you swear and curse. When you're chewing on life's gristle, don't grumble; give a whistle, and this'll help things turn out for the best. And... always look on the bright side of life... 
— Guess who?

<h1>Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numerical-computing-in-Python" data-toc-modified-id="Numerical-computing-in-Python-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numerical computing in Python</a></span><ul class="toc-item"><li><span><a href="#Indexing-and-accessing-arrays" data-toc-modified-id="Indexing-and-accessing-arrays-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Indexing and accessing arrays</a></span></li><li><span><a href="#Manipulating-arrays" data-toc-modified-id="Manipulating-arrays-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Manipulating arrays</a></span><ul class="toc-item"><li><span><a href="#Replacing,-adding-or-deleting-elements" data-toc-modified-id="Replacing,-adding-or-deleting-elements-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Replacing, adding or deleting elements</a></span></li><li><span><a href="#Flattening-or-reshaping-arrays" data-toc-modified-id="Flattening-or-reshaping-arrays-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Flattening or reshaping arrays</a></span></li></ul></li><li><span><a href="#Pre-allocating-arrays" data-toc-modified-id="Pre-allocating-arrays-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Pre-allocating arrays</a></span></li><li><span><a href="#scipy-matrices" data-toc-modified-id="scipy-matrices-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span><code>scipy</code> matrices</a></span><ul class="toc-item"><li><span><a href="#Matrix-vector-operations" data-toc-modified-id="Matrix-vector-operations-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Matrix-vector operations</a></span></li></ul></li><li><span><a href="#Two-useful-scipy-sub-packages" data-toc-modified-id="Two-useful-scipy-sub-packages-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Two useful <code>scipy</code> sub-packages</a></span><ul class="toc-item"><li><span><a href="#sc.stats" data-toc-modified-id="sc.stats-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span><code>sc.stats</code></a></span></li><li><span><a href="#sc.integrate" data-toc-modified-id="sc.integrate-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span><code>sc.integrate</code></a></span><ul class="toc-item"><li><span><a href="#The-Lotka-Volterra-model" data-toc-modified-id="The-Lotka-Volterra-model-1.5.2.1"><span class="toc-item-num">1.5.2.1&nbsp;&nbsp;</span>The Lotka-Volterra model</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#The-need-for-speed:-Profiling-in-Python" data-toc-modified-id="The-need-for-speed:-Profiling-in-Python-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>The need for speed: Profiling in Python</a></span><ul class="toc-item"><li><span><a href="#Profiling" data-toc-modified-id="Profiling-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Profiling</a></span></li><li><span><a href="#Quick-profiling-with-timeit" data-toc-modified-id="Quick-profiling-with-timeit-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Quick profiling with <code>timeit</code></a></span></li></ul></li><li><span><a href="#Practicals" data-toc-modified-id="Practicals-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Practicals</a></span><ul class="toc-item"><li><span><a href="#Lotka-Volterra-model-problem" data-toc-modified-id="Lotka-Volterra-model-problem-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Lotka-Volterra model problem</a></span></li></ul></li><li><span><a href="#Networks-in-python" data-toc-modified-id="Networks-in-python-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Networks in <code>python</code></a></span></li><li><span><a href="#Practicals" data-toc-modified-id="Practicals-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Practicals</a></span></li><li><span><a href="#Regular-expressions-in-python" data-toc-modified-id="Regular-expressions-in-python-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Regular expressions in <code>python</code></a></span><ul class="toc-item"><li><span><a href="#Metacharacters-vs.-regular-characters" data-toc-modified-id="Metacharacters-vs.-regular-characters-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Metacharacters vs. regular characters</a></span></li><li><span><a href="#regex-elements" data-toc-modified-id="regex-elements-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>regex elements</a></span></li><li><span><a href="#regex-in-python" data-toc-modified-id="regex-in-python-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>regex in <code>python</code></a></span></li><li><span><a href="#Some-RegExercises" data-toc-modified-id="Some-RegExercises-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Some RegExercises</a></span></li><li><span><a href="#Important-re-functions" data-toc-modified-id="Important-re-functions-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Important <code>re</code> functions</a></span></li></ul></li><li><span><a href="#Practicals" data-toc-modified-id="Practicals-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Practicals</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Blackbirds-problem" data-toc-modified-id="Blackbirds-problem-7.0.1"><span class="toc-item-num">7.0.1&nbsp;&nbsp;</span>Blackbirds problem</a></span></li></ul></li></ul></li><li><span><a href="#Databases-and-python" data-toc-modified-id="Databases-and-python-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Databases and <code>python</code></a></span><ul class="toc-item"><li><span><a href="#Relational-databases" data-toc-modified-id="Relational-databases-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>Relational databases</a></span></li><li><span><a href="#SQLite" data-toc-modified-id="SQLite-8.2"><span class="toc-item-num">8.2&nbsp;&nbsp;</span>SQLite</a></span></li><li><span><a href="#SQLite-with-python" data-toc-modified-id="SQLite-with-python-8.3"><span class="toc-item-num">8.3&nbsp;&nbsp;</span>SQLite with python</a></span></li></ul></li><li><span><a href="#Using-Python-to-build-workflows" data-toc-modified-id="Using-Python-to-build-workflows-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Using Python to build workflows</a></span><ul class="toc-item"><li><span><a href="#Using-subprocess" data-toc-modified-id="Using-subprocess-9.1"><span class="toc-item-num">9.1&nbsp;&nbsp;</span>Using <code>subprocess</code></a></span></li><li><span><a href="#Running-R" data-toc-modified-id="Running-R-9.2"><span class="toc-item-num">9.2&nbsp;&nbsp;</span>Running <code>R</code></a></span></li></ul></li><li><span><a href="#Practicals" data-toc-modified-id="Practicals-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Practicals</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Using-os-problem-1" data-toc-modified-id="Using-os-problem-1-10.0.1"><span class="toc-item-num">10.0.1&nbsp;&nbsp;</span>Using <code>os</code> problem 1</a></span></li><li><span><a href="#Using-os-problem-2" data-toc-modified-id="Using-os-problem-2-10.0.2"><span class="toc-item-num">10.0.2&nbsp;&nbsp;</span>Using <code>os</code> problem 2</a></span></li></ul></li></ul></li><li><span><a href="#Practicals-wrap-up" data-toc-modified-id="Practicals-wrap-up-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Practicals wrap-up</a></span></li><li><span><a href="#Readings-and-Resources" data-toc-modified-id="Readings-and-Resources-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Readings and Resources</a></span></li></ul></div>

In this chapter, we will build on the [previous chapter](05-Python_I.ipynb). We cover some more advanced topics that will round-off your training in Biological Computing in Python. 

## Numerical computing in Python

The python package `scipy` can help you do serious number crunching including,

* Linear algebra (matrix and vector operations)
* Numerical integration (Solving ODEs)
* Fourier transforms
* Interpolation
* Calculating special functions (incomplete Gamma, Bessel, etc.)
* Generation of random numbers
* Using statistical functions and transformations

In the following, we will use the `array` data structure in `scipy` for data manipulations and calculations. Scipy
arrays are objects, and are similar in some respects to python lists, but are more naturally multidimensional, homogeneous in type (the default is float), and allow efficient (fast) manipulations. Thus scipy arrays are analogous to the R `matrix` data object/structure.

The same array objects are accessible within the `numpy` package, which is a subset of `scipy`.

So let's try `scipy`:

In [10]:
import scipy as sc

In [11]:
a = sc.array(range(5)) # a one-dimensional array
a

array([0, 1, 2, 3, 4])

In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(type(a[0]))

<class 'numpy.int64'>


Thus the last two outputs tell you that firstly, there is a data structure type (and a class) called `numpy.ndarray`, and secondly, that at position `0` (remember, Pthin indexing starts at 0) it holds an [64 bit integer](https://en.wikipedia.org/wiki/9,223,372,036,854,775,807). All elements in `a` will be of type `int` because that is what `range()` returns (try `?range`).

![A graphical depiction of numpy/scipy arrays, which can have multiple
dimensions (even greater than 3). From
<http://pages.physics.cornell.edu/~myers/teaching/ComputationalMethods/python/arrays.html>](./graphics/numpyarray.png)

You can also specify the data type of the array:

In [15]:
a = sc.array(range(5), float)
a

array([ 0.,  1.,  2.,  3.,  4.])

In [16]:
a.dtype # Check type 

dtype('float64')

You can also get a 1-D arrays as follows:

In [17]:
x = sc.arange(5)
x

array([0, 1, 2, 3, 4])

In [19]:
x = sc.arange(5.) #directly specify float using decimal
x

array([ 0.,  1.,  2.,  3.,  4.])

As with other Python variables (e.g., created as a list or a dictionary), you can apply methods to variables created as scipy arrays. For example, type `x.` and hit TAB to see all methods you can apply to`x`. To see dimensions of `x`:

In [28]:
x.shape

(5,)

Remember, you can type `:?x.methodname` to get info on a particular method. For example, try `?x.shape`.

You can also convert to and from Python lists:

In [33]:
b = sc.array([i for i in range(10) if i%2==1]) #odd numbersbetween 1 and `0 
b

array([1, 3, 5, 7, 9])

In [34]:
c = b.tolist() #convert back to list
c

[1, 3, 5, 7, 9]

To make a matrix, you need a 2-D scipy array:

In [42]:
mat = sc.array([[0, 1], [2, 3]])
mat

array([[0, 1],
       [2, 3]])

In [43]:
mat.shape

(2, 2)

### Indexing and accessing arrays

As with other Python data objects such as lists, scipy array elements can be accessed using square brackets (`[ ]`) with the `[row,column]` reference. Indexing of scipy arrays works like that for other data structures, with index values starting at 0. So, you can obtain all the elements of a particular row as:

In [36]:
mat[1] # accessing whole 2nd row, remember indexing starts at  0

array([2, 3])

In [37]:
mat[:,1] #accessing whole second column  

array([1, 3])

And accessing particular elements:

In [38]:
mat[0,0] # 1st row, 1st column element

0

In [39]:
mat[1,0] # 2nd row, 1st column element

2

Note that (like all other programming languages) row index always comes before column index. That is, `mat[1]` is always going to mean "whole second row", and `mat[1,1]` means 1st row and 1st column element. Therefore, to access the whole second column, you need:

In [40]:
mat[:,0] #accessing whole first column  

array([0, 2])

Python indexing also accepts negative values for going back to the start
from the end of an array:

In [44]:
mat[0,1]

1

In [45]:
mat[0,-1] #interesting!

1

In [46]:
mat[0,-2] #very interesting, perhaps useless!

0

### Manipulating arrays

Manipulating scipy arrays is pretty straightforward. 

---
> **Why scipy/numpy arrays are computationally efficient:**  The data associated with numpy array object (its metadata  - number of dimensions, shape, data type, etc - as well as the actual data) are stored in a homogeneous and contiguous block of memory (a "data buffer"), at a particular address in the system's RAM (Random Access Memory). This makes numpy arrays more efficient than a pure Python data structures like lists whose data are scattered across the system memory.

---

#### Replacing, adding or deleting elements

Let's look at how you can replace, add, or delete an array element (a single entry, or whole row(s) or whole column(s)):

In [47]:
mat[0,0] = -1 #replace a single element
mat

array([[-1,  1],
       [ 2,  3]])

In [48]:
mat[:,0] = [12,12] #replace whole column
mat

array([[12,  1],
       [12,  3]])

In [49]:
sc.append(mat, [[12,12]], axis = 0) #append row, note axis specification

array([[12,  1],
       [12,  3],
       [12, 12]])

In [50]:
sc.append(mat, [[12],[12]], axis = 1) #append column

array([[12,  1, 12],
       [12,  3, 12]])

In [51]:
newRow = [[12,12]] #create new row

In [53]:
mat = sc.append(mat, newRow, axis = 0) #append that existing row
mat

array([[12,  1],
       [12,  3],
       [12, 12],
       [12, 12]])

In [54]:
sc.delete(mat, 2, 0) #Delete 3rd row

array([[12,  1],
       [12,  3],
       [12, 12]])

And concatenation:

In [55]:
mat = sc.array([[0, 1], [2, 3]])
mat0 = sc.array([[0, 10], [-1, 3]])
sc.concatenate((mat, mat0), axis = 0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [-1,  3]])

#### Flattening or reshaping arrays

You can also "flatten" or "melt" arrays, that is, change array dimensions (e.g., from a matrix to a vector):

In [57]:
mat.ravel() # NOTE: ravel is row-priority - happens row by row

array([0, 1, 2, 3])

In [58]:
mat.reshape((4,1)) # this is different from ravel - check ?sc.reshape

array([[0],
       [1],
       [2],
       [3]])

In [60]:
mat.reshape((1,4)) # NOTE: reshaping is also row-priority

array([[0, 1, 2, 3]])

In [61]:
mat.reshape((3, 1)) # But total elements must remain the same!

ValueError: cannot reshape array of size 4 into shape (3,1)

This is a bit different than how `R` behaves ([Next Chapter]()), where you won't get an error (R "recycles" data), which is more dangerous!

### Pre-allocating arrays

As in other computer languages, it is usually more efficient to preallocate an array () rather than append / insert / concatenate additional elements, rows, or columns (*why* - because you might run out of contiguous space in the specific system memory (RAM) address where the current array is stored). For example, if you know the size of your matrix or array, you can initialize it with ones or zeros:

In [62]:
sc.ones((4,2)) #(4,2) are the (row,col) array dimensions

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [63]:
sc.zeros((4,2)) # or zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [64]:
m = sc.identity(4) #create an identity matrix
m

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [65]:
m.fill(16) #fill the matrix with 16
m

array([[ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.]])

### `scipy` matrices

Scipy also has a `matrix` data structure class. Scipy matrices are strictly 2-Dimensional, while scipy arrays are
N-Dimensional. Matrix objects are a subclass of scipy arrays, so they inherit all the attributes and methods of scipy arrays (ndarrays).

The main advantage of scipy matrices is that they provide a convenient notation for matrix multiplication: if a and b are matrices, then a*b is their matrix product.

#### Matrix-vector operations

Now let's perform some common matrix-vector operations on arrays (you can also try the same using matrices instead of arrays):

In [106]:
mm = sc.arange(16)
mm = mm.reshape(4,4) #Convert to matrix
mm

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
mm.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [108]:
mm + mm.transpose()

array([[ 0,  5, 10, 15],
       [ 5, 10, 15, 20],
       [10, 15, 20, 25],
       [15, 20, 25, 30]])

In [109]:
mm - mm.transpose()

array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [110]:
mm * mm.transpose() ## Note: Elementwise multiplication!

array([[  0,   4,  16,  36],
       [  4,  25,  54,  91],
       [ 16,  54, 100, 154],
       [ 36,  91, 154, 225]])

In [111]:
mm // mm.transpose() # Note the integer division

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([[0, 0, 0, 0],
       [4, 1, 0, 0],
       [4, 1, 1, 0],
       [4, 1, 1, 1]])

In [112]:
mm * sc.pi

array([[  0.        ,   3.14159265,   6.28318531,   9.42477796],
       [ 12.56637061,  15.70796327,  18.84955592,  21.99114858],
       [ 25.13274123,  28.27433388,  31.41592654,  34.55751919],
       [ 37.69911184,  40.8407045 ,  43.98229715,  47.1238898 ]])

In [113]:
mm.dot(mm) # MATRIX MULTIPLICATION

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [114]:
mm = sc.matrix(mm) # convert to scipy matrix class
mm

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [115]:
mm*mm # now matrix multiplication is syntactically easier

matrix([[ 56,  62,  68,  74],
        [152, 174, 196, 218],
        [248, 286, 324, 362],
        [344, 398, 452, 506]])

We can do a lot more by importing the `linalg` sub-package: `sc.linalg` (try it).

### Two useful `scipy` sub-packages

Two particularly useful `scipy` sub-packages are `sc.integrate` (*what will I need this for?*) and `sc.stats`. *Why not use `R` for this?* — because often you might just want to calculate some summary stats of your simulation results within Python.

#### `sc.stats`

Let's take a quick spin in `sc.stats`.

In [116]:
import scipy.stats

In [117]:
scipy.stats.norm.rvs(size = 10) # 10 samples from N(0,1)

array([-1.11040676,  1.46218105, -1.31862249,  1.46861139, -0.98276766,
       -0.23966559,  2.04260073, -0.42014852, -1.11174925, -0.67510441])

In [118]:
scipy.stats.randint.rvs(0, 10, size =7) # Random integers between 0 and 10

array([2, 3, 7, 6, 6, 7, 3])

#### `sc.integrate`

Numerical integration is the approximate computation of an integral using numerical techniques. You need numerical integration whenever you have a complicated function that cannot be integrated analytically using
anti-derivatives. A common application is solving ordinary differential equations (ODEs), commonly used for modelling biological systems.

##### The Lotka-Volterra model
Let's try `sc.integrate` for solving a classical model in biology — the Lotka-Volterra model for a predator-prey system.

$\star$ Create `LV1.py` in your weekly directory and run it.

The Lotka-Volterra model is: $$\label{eqn:LVMod}
\begin{aligned}
    \frac{dR}{dt} &= r R - a C R \\
    \frac{dC}{dt} &= - z C + e a C R
\end{aligned}$$

where $C$ and $R$ are consumer (e.g., predator) and resource (e.g., prey) population sizes (either biomass or numbers), $r$ is the intrinsic growth rate of the resource population, $a$ is a "search rate" that determines the encounter rate between consumer and resource, $z$ is mortality rate and $e$ is the consumer's efficiency in converting resource to consumer biomass.

`LV1.py` runs (numerically solves the ODE) this model and plots the equilbrium. Have good look at the code, line by line, and make sure that you understand what's going on. A subsequent practical will require you to use this code to simulate modified version of the LV model.

## The need for speed: Profiling in Python

Donald Knuth says: *Premature optimization is the root of all evil*. Indeed, computational speed may not be your initial concern. Also, you should focus on developing clean, reliable, reusable code rather than worrying first about how fast your code runs. However, speed will become an issue when and if your analysis or modeling becomes
complex enough (e.g., food web or large network simulations). In that case, knowing which parts of your code take the most time is useful – optimizing those parts may save you lots of time. To find out what is slowing down your code you need to use "profiling".

### Profiling

Profiling is easy in `ipython` – simply use the command: 

```python
%run -p your_function_name
```

Let's write a simple illustrative program and name it `profileme.py`:
```python
def a_useless_function(x):
    y = 0 
    for i in range(100000000): # eight zeros! 
        y = y + i
    return 0

def another_useless_function(x):
    y = 0 
    z = 0 # start a counter
    while z <= 100000000: # eight zeros!
        y = y + x
        z += 1
    return 0
    
def a_less_useless_function(x):
    y = 0 
    for i in range(100000):# five zeros!
        y = y + i
    return 0

def some_function(x):
    print(x)
    a_useless_function(x)
    another_useless_function(x)
    a_less_useless_function(x)
    return 0

some_function(1000)
```
Now run it with `run -p profileme.py`, and you should see something like: 

```bash
      95 function calls (94 primitive calls) in 14.931 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    9.347    9.347    9.347    9.347 profileme.py:7(another_useless_function)
        1    5.577    5.577    5.577    5.577 profileme.py:1(a_useless_function)
        1    0.005    0.005    0.005    0.005 profileme.py:15(a_less_useless_function)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.compile}
   [more output]
```

The function `range` is taking long – we should use `xrange` instead. When iterating over a large number of
values, `xrange`, unlike `range`, does not create all the values before iteration, but creates them "on demand" (ie.e., `xrange` is a "generator"). Range creates a list, so if you do `range(1, 10000000)` it creates a list in memory with 10000000 elements. For example, `range(1000000)`yields a 4Mb+ list.

So let's modify the script:

```python
def a_useless_function(x):
    y = 0
    for i in xrange(100000000): # eight zeros!
        y = y + i
    return 0

def another_useless_function(x):
    y = 0 
    z = 0 # start a counter
    while z <= 100000000: # eight zeros!
        y = y + x
        z += 1
    return 0
    
def a_less_useless_function(x):
    y = 0 
    for i in xrange(100000): # five zeros!
        y = y + i
    return 0

def some_function(x):
    print(x)
    a_useless_function(x)
    another_useless_function(x)
    a_less_useless_function(x)
    return 0

some_function(1000)
```

Again running the program with the command `run -p` yields:

So we saved 1.499 s! (not enough to grab a pint, but ah well...).

### Quick profiling with `timeit`

Alternatively, if you are writing your script and want to figure out what the best way to do something (say a particular command or a loop) might be, then you can use `timeit`.

Type an run the following code in a python script called `timeitme.py`:

```python
##############################################################################
# range vs. xrange.
##############################################################################
import time
import timeit

def a_not_useful_function():
    y = 0
    for i in range(100000):
        y = y + i
    return 0

def a_less_useless_function():
    y = 0
    for i in xrange(100000):
        y = y + i
    return 0

# One approach is to time it like this:
start = time.time()
a_not_useful_function()
print "a_not_useful_function takes %f s to run." % (time.time() - start)

start = time.time()
a_less_useless_function()
print "a_less_useless_function takes %f s to run." % (time.time() - start)

# But you'll notice that if you run it multiple times, the time taken changes a
# bit. So instead, you can also run:
#   %timeit a_not_useful_function()
#   %timeit a_less_useless_function()
# in iPython.

##############################################################################
# for loops vs. list comprehensions.
##############################################################################

my_list = range(1000)

def my_squares_loop(x):
    out = []
    for i in x:
        out.append(i ** 2)
    return out


def my_squares_lc(x):
    out = [i ** 2 for i in x]
    return out

# %timeit my_squares_loop(my_list)
# %timeit my_squares_lc(my_list)


##############################################################################
# for loops vs. join method.
##############################################################################

import string
my_letters = list(string.ascii_lowercase)

def my_join_loop(l):
    out = ''
    for letter in l:
        out += letter
    return out


def my_join_method(l):
    out = ''.join(l)
    return out

# %timeit(my_join_loop(my_letters))
# %timeit(my_join_method(my_letters))


##############################################################################
# Oh dear.
##############################################################################

def getting_silly_pi():
    y = 0
    for i in xrange(100000):
        y = y + i
    return 0


def getting_silly_pii():
    y = 0
    for i in xrange(100000):
        y += i
    return 0

# %timeit(getting_silly_pi())
# %timeit(getting_silly_pii())
```
Now run it these different instances of timeit-ing by tying the `%timeit` command followed by the function call. Note that you can import all the functions using `from timeitme import *`

But remember, don't go crazy with profiling for the sake of shaving a couple of milliseconds, tempting as that may be!

## Practicals

As always, test, add, commit and push all your new code and data to your git repository.

### Lotka-Volterra model problem

Copy and modify `LV1.py` into another script called `LV2.py` that does the following:

1.  Take arguments for the four LV model parameters $r$, $a$, $z$ ,$e$ from the command line:
```
LV2.py arg1 arg2 ... etc
```
2.  Runs the Lotka-Volterra model with prey density dependence $r R (1 - \frac{R} {K})$, which changes the coupled ODEs to,

\begin{aligned}
    \frac{dR}{dt} &= r R (1 - \frac{R} {K}) - a C R \\
    \frac{dC}{dt} &= - z C + e a C R
\end{aligned}

3.  Saves the plot as `.pdf` in an external results directory
    in your weekly directory

4.  The chosen parameter values should show in the plot (e.g.,
    $r = 1, a = .5 $, etc) You can change time length $t$ too.

5.  Include a script in `Code` that will run both
    `LV1.py` and `LV2.py` with
    appropriate arguments. This script should also profile the two
    scripts and print the results to screen for each of the scripts
    using the `%run -p` approach. Look at and compare the
    speed bottlenecks in `LV1.py` and `LV2.py`.
    Think about how you could further speed up the scripts.

*Write every subsequent extra credit script file with a new name such as `LV3.py`,`LV4.py`, etc.* 

**Extra credit**: Choose appropriate values for the parameters such that both predator and prey persist with prey density dependence — the final (non-zero) population values should be printed to screen.

**Extra-extra credit**: Write a discrete-time version of the LV model called `LV3.py`. The discrete-time model is:

\begin{align} 
    R_{t+1} &= R_t (1 + r \left(1 - \frac{R_t}{K}\right) - a C_t)\\ 
    C_{t+1} &= C_t (1 - z + e a R_t) 
\end{align}

Include this script in `run_LV.py`, and profile it as well.

`**Extra-extra-extra credit**`: Write a version of the discrete-time model (eqn \[eqn:LVDisc\]) simulation with a random gaussian fluctuation in resource's growth rate at each time-step:

\begin{aligned}
        R_{t+1} &= R_t (1 + (r + \epsilon) \left(1 - \frac{R_t}{K}\right)- a C_t)\\
        C_{t+1} &= C_t (1 - z + e a R_t)
\end{aligned}

where $\epsilon$ is a random fluctuation drawn from a gaussian distribution (use `sc.stats`). Include this
script in ` run_LV.py`, and profile it as well.

You can also add fluctuations to both populations simultaneously this
way: 
\begin{aligned}
    R_{t+1} &= R_t (1 + \epsilon + r +  \left(1 - \frac{R_t}{K}\right) - a C_t)\\
    C_{t+1} &= C_t (1 - z + \epsilon + e a R_t)
\end{aligned}

## Networks in `python`

ALL biological systems have a network representation, consisting of nodes for the biological entities of interest, and edges or links for the relationships between them. Here are some examples:
* Metabolic networks
* Gene regulatory networks
* Individual-Individual (e.g., social networks)
* Food webs
* Pollination networks

*Can you think of a few more examples from biology?*

You can easily simulate, analyze, and visualize biological networks inboth `python` and `R` using some nifty packages. A full network anaalysis tutorial is out of the scope of our Python module's objectives, but let's try a simple visualization using the ` networkx` python package.

For this you need to first install the package:

```bash
sudo apt-get install python-networkx
```

In [ ]:
$ sudo apt-get install python-networkx  

Now type the code file `DrawFW.py` and run it:

Look thorugh the code carefully (line-by-line) as there are some new
python objects introduced by `networkx` for storing node and
edge data.

Practicals
----------

You can also do nice network visualizations in R. Here you will convert
a network visualization script written in `R` using the
` igraph` package to a python script that does the same
thing.

First copy the script file called `Nets.R` and the data files
it calls and run it. This script visualizes the QMEE CDT collaboration
network (see <http://www.imperial.ac.uk/qmee-cdt/>), coloring the the
nodes by the type of node (organization type: "University","Hosting
Partner", "Non-hosting Partner").

Now, convert this script to a `python` script that does the
same thing, including writing to an `.svg` file using the
same QMEE CDT link and node data. You can use `networkx` or
some other python network visualization package.

Regular expressions in `python`
------------------------------------------

Let's shift gears now, and look at a very important skill that you
should learn, or at least be aware of — `*Regular
expressions*`. Regular expressions (regex) are a tool to find
patterns in strings, such as:

Finding DNA motifs in sequence data

Navigating through files in a directory

Parsing text files

Extracting information from html and xml files

Thus, if you are interested in data mining, need to clean or process
data in any other way, or convert a bunch of information into usable
data, knowing regex is necessary.

\
[www.xkcd.com/208/](www.xkcd.com/208/)

Regex packages are available for most programming languages
(`grep` in UNIX / Linux, where regex first became popular).

### Metacharacters vs. regular characters

A regex may consist of a combination of "metacharacters" (modifiers) and
"regular" or literal characters. There are 14 metacharacters: ` \[
\] { } ( ) \\  \^ \$ . $\vert$ ? \* + ` These metacharacters do
special things, for example:

means match target to `1` and if that does not match then
match target to `2`

means match to any character in range `0` to `9`

means anything except upper or lower case ` f` and means
everything except lower case `a` to `z`

Everything else is interpreted literally (e.g., `a` is
matched by entering `a` in the regex).

`\[ ` and `\] `, specify a character "class" — the
set of characters that you wish to match. Metacharacters are not active
inside classes. For example, will match any of the characters
`a` to `z`, but also `\$`, because
inside a character class it loses its special metacharacter status.

### regex elements

A useful (not exhaustive) list of regex elements is:

  ---------------------------- ----------------------------------------------------------------------------------------------------------------------------------
  `a`               match the character `a`
  `3`               match the number `3`
  `$\backslash$n`   match a newline
  `$\backslash$t`   match a tab
  `$\backslash$s`   match a whitespace
  `.`               match any character except line break (newline)
  `$\backslash$w`   match any alphanumeric character (including underscore)
  `$\backslash$W`   match any character not covered by ` $\backslash$w` (i.e., match any non-alphanumeric character excluding underscore)
  `$\backslash$d`   match a numeric character
  `$\backslash$D`   match any character not covered by ` $\backslash$d` (i.e., match a non-digit)
                               match any character listed: `a`, `t`, `g`, `c`
  `at|gc`           match `at` or `gc`
                               any character not listed: any character but `a`, `t`, `g`, `c`
  `?`               match the preceding pattern element zero or one times
                               match the preceding pattern element zero or more times
  `+`               match the preceding pattern element one or more times
  `{n}`             match the preceding pattern element exactly `n` times
  `{n,}`            match the preceding pattern element at least `n` times
  `{n,m}`           match the preceding pattern element at least `n` but not more than `m` times
  `\^`              match the beginning of a line
  `\$`              match the end of a line
  ---------------------------- ----------------------------------------------------------------------------------------------------------------------------------

### regex in `python`

Regex functions in python are in the module `re` — so we will
`import re`. The simplest `python` regex function
is ` re.search`, which searches the string for match to a
given pattern — returns a *match object* if a match is found and
`None` if not.

`**Always**` put `r` in front of your regex — it
tells python to read the regex in its "raw" (literal) form. Without raw
string notation (r"text"), every backslash ('\\') in a regular
expression would have to be prefixed with another one to escape it.

From <https://docs.python.org/2/library/re.html>: `*If you're not
using a raw string to express the pattern, remember that Python also
uses the backslash as an escape sequence in string literals; if the
escape sequence isn't recognized by Python's parser, the backslash and
subsequent character are included in the resulting string. However, if
Python would recognize the resulting sequence, the backslash should be
repeated twice. This is complicated and hard to understand, so it's
highly recommended that you use raw strings for all but the simplest
expressions.*`

OK, let's try some regexes (type all that follows in `
Code/regexs.py`):

To know whether a pattern was matched, we can use an `if`:

In [ ]:
MyStr = 'an example'

match = re.search(r'\w*\s', MyStr)

if match:                      
    print 'found a match:', match.group() 
else:
    print 'did not find a match'    

Here are some more regexes (add all that follows to the
`Code/regexs.py`):

![In case you were wondering what `*Theloderma asper*`, the
"bird-shit frog", looks like. I snapped this one in North-east India
ages ago](thelodermaasper.JPG){width=".5\textwidth"}

You can group regexes into meaningful blocks using parentheses. For
example, let's try matching a string consisting of an academic's name,
email address and research area or interest (no need to type this into
any python file):

In [ ]:
MyStr = 'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and 
ecological theory'

# without groups
match = re.search(r"[\w\s]*,\s[\w\.@]*,\s[\w\s&]*",MyStr)

match.group()
'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and ecological theory'

match.group(0)
'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and ecological theory'

# now add groups using ( )
match = re.search(r"([\w\s]*),\s([\w\.@]*),\s([\w\s&]*)",MyStr)

match.group(0)
'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and ecological theory'

match.group(1)
'Samraat Pawar'

match.group(2)
's.pawar@imperial.ac.uk'

match.group(3)
'Systems biology and ecological theory'

Have a look at `re4.py` in your code repository for more on
parsing email addresses using regexes.

### Some RegExercises

These exercises are not for submission as part of your coursework, but
we will discuss them in class (in a later week).

Translate the following regular expressions into regular English (don't
type this in `regexs.py`)!

In [ ]:
r'^abc[ab]+\s\t\d'
% 'abca \t1'

r'^\d{1,2}\/\d{1,2}\/\d{4}$'
% '11/12/2004'

r'\s*[a-zA-Z,\s]+\s*'
% ' aBz  '

Write a regex to match dates in format YYYYMMDD, making sure that:

Only seemingly valid dates match (i.e., year greater than 1900)

First digit in month is either 0 or 1

First digit in day $\leq$ 3

### Important `re` functions

  -------------------------------------- -----------------------------------------------------------------------------------------------------------------------------------------------------------
  `re.compile(reg)`           Compile a regular expression. In this way the pattern is stored for repeated use, improving the speed.
  `re.search(reg, text)`      Scan the string and find the first match of the pattern in the string. Returns a `match` object if successful and `None` otherwise.
  `re.match(reg, text)`       as `re.search`, but only match the beginning of the string.
  `re.split(ref, text)`       Split the text by the occurrence of the pattern described by the regular expression.
  `re.findall(ref, text)`     As `re.search`, but return a list of all the matches. If groups are present, return a list of groups.
  `re.finditer(ref, text)`    As `re.search`, but return an iterator containing the next match.
  `re.sub(ref, repl, text)`   Substitute each non-overlapping occurrence of the match with the text in `repl` (or a function!).
  -------------------------------------- -----------------------------------------------------------------------------------------------------------------------------------------------------------

Practicals
----------

As always, test, add, commit and push all your new code and data to your
git repository.

#### Blackbirds problem

Complete the code `blackbirds.py` that you find in the `
CMEEMasteRepo` (necessary data file is also there).

Databases and `python`
---------------------------------

Many of you will deal with complex data — and often, lots of it.
Ecological and Evolutionary data are particularly complex because they
contain large numbers of attributes, often measured in very different
scales and units for individual taxa, populations, etc. In this
scenario, storing the data in a database makes a lot of sense! You can
easily include the database in your analysis workflow — indeed, that's
why people use databases. And you can use python (and R) to build,
manipulate and use your database.

### Relational databases

A `*relational*` database is a collection of interlinked
(` *related*`) tables that altogether store a complex dataset
in a logical, computer-readable format. Dividing a dataset into multiple
tables minimizes redundancies. For example, if your data were sampled
from three sites — then, rather than repeating the site name and
description in each row in a text file, you could just specify a
numerical "key" that directs to another table containing the sampling
site name and description.

Finally, if you have many rows in your data file, the type of sequential
access we have been using in our `python` and `R`
scripts is inefficient — you should be able to instantly access any row
regardless of its position

Data columns in a database are usually called `*fields*`,
while the rows are the `*records*`. Here are a few things to
keep in mind about databases:

Each field typically contains only one data type (e.g., integers,
floats, strings)

Each record is a "data point", composed of different values, one for
each field — somewhat like a python tuple

Some fields are special, and are called `*keys*`:

The `*primary key*` uniquely defines a record in a table
(e.g., each row is identified by a unique number)

To allow fast retrieval, some fields (and typically all the keys) are
indexed — a copy of certain columns that can be searched very
efficiently

`*Foreign keys*` are keys in a table that are primary keys in
another table and define relationships between the tables

The key to designing a database is to minimize redundancy and dependency
without losing the logical consistency of tables — this is called
`*normalization*` (arguably more of an art than a science!)

Let's look at a simple example.

Imagine you recorded body sizes of species from different field sites in
a single text file (e.g., a `.csv` file) with the following
fields:

  -------------------------------- ---------------------------------------------
  `ID`                  Unique ID for the record
  `SiteName`            Name of the site
  `SiteLong`            Longitude of the site
  `SiteLat`             Latitude of the site
  `SamplingDate`        Date of the sample
  `SamplingHour`        Hour of the sampling
  `SamplingAvgTemp`     Average air temperature on the sampling day
  `SamplingWaterTemp`   Temperature of the water
  `SamplingPH`          PH of the water
  `SpeciesCommonName`   Species of the sampled individual
  `SpeciesLatinBinom`   Latin binomial of the species
  `BodySize`            Width of the individual
  `BodyWeight`          Weight of the individual
  -------------------------------- ---------------------------------------------

\
It would be logical to divide the data into four tables:

`*Site table*`:\

  ----------------------- -----------------------
  `SiteID`     ID for the site
  `SiteName`   Name of the site
  `SiteLong`   Longitude of the site
  `SiteLat`    Latitude of the site
  ----------------------- -----------------------

\
`*Sample table*`:\

  -------------------------------- --------------------------
  `SamplingID`          ID for the sampling date
  `SamplingDate`        Date of the sample
  `SamplingHour`        Hour of the sample
  `SamplingAvgTemp`     Average air temperature
  `SamplingWaterTemp`   Temperature of the water
  `SamplingPH`          PH of the water
  -------------------------------- --------------------------

\
`*Species table*`:\

  -------------------------------- -------------------------------
  `SpeciesID`           ID for the species
  `SpeciesCommonName`   Species name
  `SpeciesLatinBinom`   Latin binomial of the species
  -------------------------------- -------------------------------

\
`*Individual table*`:\

  --------------------------- -------------------------------
  `IndividualID`   ID for the individual sampled
  `SpeciesID`      ID for the species
  `SamplingID`     ID for the sampling day
  `SiteID`         ID for the site
  `BodySize`       Width of the individual
  `BodyWeight`     Weight of the individual
  --------------------------- -------------------------------

\
In each table, the first ID field is the primary key. The last table
contains three foreign keys because each individual is associated with
one species, one sampling day and one sampling site.

These structural features of a database are called its
`*schema*`.

### SQLite

`SQLite` is a simple (and very popular) SQL (Structured Query
Language)-based solution for managing localized, personal databases. I
can safely bet that most, if not all of you unknowingly (or knowingly!)
use `SQLite` — it is used by MacOSX, Firefox, Acrobat Reader,
iTunes, Skype, iPhone, etc. SQLite is also the database "engine"
underlying your Siwlood Masters Web App: <http://silwoodmasters.co.uk>

We can easily use SQLite through Python scripts. First, install SQLite
by typing in the Ubuntu terminal:

In [ ]:
$ sudo apt-get install sqlite3 libsqlite3-dev

Also, make sure that you have the necessary package for python by typing
`import sqlite3` in the python or ipython shell. Finally, you
may install a GUI for SQLite3 :

In [ ]:
$ sudo apt-get install sqliteman

Now type `sqlite3` in the Ubuntu terminal to check if SQLite
successfully launches.

SQLite has very few data types (and lacks a boolean and a date type):

  ---------------------- ----------------------------------------------------------------------------------------------------------------------
  `NULL`      The value is a NULL value
  `INTEGER`   The value is a signed integer, stored in up to or 8 bytes
  `REAL`      The value is a floating point value, stored as in 8 bytes
  `TEXT`      The value is a text string
  `BLOB`      The value is a blob of data, stored exactly as it was input (useful for binary types, such as bitmap images or pdfs)
  ---------------------- ----------------------------------------------------------------------------------------------------------------------

\
Typically, you will build a database by importing csv data — be aware
that:

Headers: the csv should have no headers

Separators: if the comma is the separator, each record should not
contain any other commas

Quotes: there should be no quotes in the data

Newlines: there should be no newlines

Now build your first database in SQLite! We will use as example a global
dataset on metabolic traits called `*Biotraits*` that we are
currently developing in our lab (should be in your `Data`
directory). This dataset contains 164 columns (fields). Thermal response
curves for different traits and species are stored in rows. This means
that site description or taxonomy are repeated as many times as
temperatures are measured in the curve. You can imagine how much
redundacy can be here!!!

For this reason, it is easier to migrate the dataset to SQL and split it
into several tables:

TCP: Includes the thermal curve performance for each species and trait
(as many rows per trait and species as temperatures have been measured
within the TCP)

TraitInfo: Contains site description and conditions under the traits
were measured (one row per thermal curve)

Consumer: Consumer description including taxonomy (one row per thermal
curve).

Resource: Resource description including taxonomy (one row per thermal
curve).

Size: Size data for each species (one row per thermal curve)

DataSource: Contains information about the data source (citation,
contributors) (one row per thermal curve).

So all these tables compose the `*Biotraits*`
`schema`.

Navigate to your `Data` directory and in an Ubuntu terminal
type:

In [ ]:
$ sqlite3 Biotraits.db
SQLite version 3.7.9
Enter ".help" for instructions
Enter SQL statements terminated with a ";"

This creates an empty database in your `Data` directory. Now,
you need to create a table with some fields. Let's start with the
`*TraitInfo*` table:

In [ ]:
sqlite> CREATE TABLE TraitInfo (Numbers integer primary key,
   ...>                                 OriginalID text,
   ...>                                 FinalID text,
   ...>                                 OriginalTraitName text,
   ...>                                 OriginalTraitDef text,
   ...>                                 Replicates integer,
   ...>                                 Habitat  integer,               
   ...>                                 Climate text,
   ...>                                 Location text,
   ...>                                 LocationType text,
   ...>                                 LocationDate text,
   ...>                                 CoordinateType text,
   ...>                                 Latitude integer,
   ...>                                 Longitude integer);

Note that I am writing all SQL commands in upper case, but it is not
necessary. I am using upper case here because SQL syntax is long and
clunky, and it quickly becomes hard to spot (and edit) commands in long
strings of complex queries.

Now let's import the dataset:

In [ ]:
sqlite> .mode csv

sqlite> .import TraitInfo.csv TraitInfo

So we built a table and imported a csv file into it. Now we can ask
SQLite to show all the tables we currently have:

In [ ]:
sqlite> .tables

TraitInfo

Let's run our first `*Query*` (note that you need a semicolon
to end a command):

In [ ]:
sqlite> SELECT * FROM TraitInfo LIMIT 5;

1,1,MTD1,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
2,1,MTD1,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
3,1,MTD1,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
4,2,MTD2,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
5,2,MTD2,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323

Let's turn on some nicer formatting:

In [ ]:
sqlite> .mode column

sqlite> .header ON

sqlite> SELECT * FROM TraitInfo LIMIT 5;

Numbers  OriginalID  FinalID     OriginalTraitName           ... 
-------  ----------  ----------  -------------------------   ...
1        1           MTD1        Resource Consumption Rate   ...
4        2           MTD2        Resource Consumption Rate   ...
6        3           MTD3        Resource Consumption Rate   ...
9        4           MTD4        Resource Mass Consumption   ...
12       5           MTD5        Resource Mass Consumption   ...

The main statement to select records from a table is
`SELECT`:

In [ ]:
sqlite> .width 40  ## NOTE: Control the width

sqlite> SELECT DISTINCT OriginalTraitName FROM TraitInfo; # Returns unique values

OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Mass-Specific Mass Consumption Rate     
Voluntary Body Velocity                 
Forward Attack Distance                 
Foraging Velocity                       
Resource Reaction Distance                   
....

sqlite> SELECT DISTINCT Habitat FROM TraitInfo
   ...> WHERE OriginalTraitName = "Resource Consumption Rate"; # Sets a condition

Habitat                                 
----------------------------------------
freshwater                              
marine                                  
terrestrial 

sqlite> SELECT COUNT (*) FROM TraitInfo;  # Returns number of rows

Count (*)           
--------------------
2336

sqlite> SELECT Habitat, COUNT(OriginalTraitName) # Returns number of rows for each group
   ...> FROM TraitInfo GROUP BY Habitat;

Habitat     COUNT(OriginalTraitName)
----------  ------------------------
NA          16                      
freshwater  609                     
marine      909                     
terrestria  802   

sqlite> SELECT COUNT(DISTINCT OriginalTraitName) # Returns number of unique values
   ...> FROM TraitInfo;

COUNT(DISTINCT OriginalTraitName)
---------------------------------
220   

sqlite> SELECT COUNT(DISTINCT OriginalTraitName) TraitCount # Assigns alias to the variable
   ...> FROM TraitInfo;

TraitCount
----------
220 

sqlite> SELECT Habitat,
   ...> COUNT(DISTINCT OriginalTraitName) AS TN
   ...> FROM TraitInfo GROUP BY Habitat;

Habitat     TN        
----------  ----------
NA          7         
freshwater  82        
marine      95        
terrestria  96     


sqlite> SELECT * # WHAT TO SELECT
   ...> FROM TraitInfo # FROM WHERE
   ...> WHERE Habitat = "marine" # CONDITIONS
   ...> AND OriginalTraitName = "Resource Consumption Rate";

Numbers     OriginalID  FinalID     OriginalTraitName          ...
----------  ----------  ----------  -------------------------  ...
778         308         MTD99       Resource Consumption Rate  ...
798         310         MTD101      Resource Consumption Rate  ...
806         311         MTD102      Resource Consumption Rate  ...
993         351         MTD113      Resource Consumption Rate  ...

The structure of the `SELECT` commend is as follows
(`*Note: `**all**` characters are case
`**in**`sensitive*`):

In [ ]:
SELECT [DISTINCT] field
FROM table
WHERE predicate
GROUP BY field
HAVING predicate
ORDER BY field
LIMIT number
;

Let's try some more elaborate queries:

In [ ]:
sqlite> SELECT Numbers FROM TraitInfo LIMIT 5;

Numbers   
----------
1         
4         
6         
9         
12      

sqlite> SELECT Numbers 
   ...> FROM TraitInfo
   ...> WHERE Numbers > 100 
   ...> AND Numbers < 200;

Numbers   
----------
107       
110       
112       
115         

sqlite> SELECT Numbers 
   ...> FROM TraitInfo
   ...> WHERE Habitat = "freshwater"
   ...> AND Number > 700
   ...> AND Number < 800;

Numbers   
----------
704       
708       
712       
716       
720       
725       
730       
735       
740       
744       
748       
      

You can also match records using something like regular expressions. In
SQL, when we use the command `LIKE`, the percent % symbol
matches any sequence of zero or more characters and the underscore
matches any single character. Similarly, `GLOB` uses the
asterisk and the underscore.

In [ ]:
sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName LIKE "_esource Consumption Rate";

OriginalTraitName        
-------------------------
Resource Consumption Rate          

sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName LIKE "Resource%";

OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Resource Reaction Distance              
Resource Habitat Encounter Rate         
Resource Consumption Probability        
Resource Mobility Selection             
Resource Size Selection                 
Resource Size Capture Intent Acceptance 
Resource Encounter Rate                 
Resource Escape Response Probability 

sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName GLOB "Resource*";


OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Resource Reaction Distance              
Resource Habitat Encounter Rate         
Resource Consumption Probability        
Resource Mobility Selection             
Resource Size Selection                 
Resource Size Capture Intent Acceptance 
Resource Encounter Rate                 
Resource Escape Response Probability 

# NOTE THAT GLOB IS CASE SENSITIVE, WHILE LIKE IS NOT

sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName LIKE "resource%";

OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Resource Reaction Distance              
Resource Habitat Encounter Rate         
Resource Consumption Probability        
Resource Mobility Selection             
Resource Size Selection                 
Resource Size Capture Intent Acceptance 
Resource Encounter Rate                 
Resource Escape Response Probability 

We can also order by any column:

In [ ]:
sqlite> SELECT OriginalTraitName, Habitat FROM 
   ...>  TraitInfo LIMIT 5;

OriginalTraitName          Habitat   
-------------------------  ----------
Resource Consumption Rate  freshwater
Resource Consumption Rate  freshwater
Resource Consumption Rate  freshwater
Resource Mass Consumption  freshwater
Resource Mass Consumption  freshwater

sqlite> SELECT OriginalTraitName, Habitat FROM 
   ...> TraitInfo ORDER BY OriginalTraitName LIMIT 5;

OriginalTraitName           Habitat   
--------------------------  ----------
48-hr Hatching Probability  marine    
Asexual Reproduction Rate   marine    
Attack Body Acceleration    marine    
Attack Body Velocity        marine    
Attack Body Velocity        marine  
 

Until now we have just queried data from one single table, but as we
have seen, the point of storing a database in SQL is that we can use
multiple tables minimizing redundancies within them. And of course,
querying data from those different tables at the same time will be
necessary at some point.

Let's import then one more table to our database:

In [ ]:
sqlite> CREATE TABLE Consumer (Numbers integer primary key,
  ...>                                OriginalID text,
  ...>                                FinalID text,
  ...>                                Consumer text,
  ...>                                ConCommon text,
  ...>                                ConKingdom text,
  ...>                                ConPhylum text,
  ...>                                ConClass text,
  ...>                                ConOrder text,
  ...>                                ConFamily text,
  ...>                                ConGenus text,
  ...>                                ConSpecies text);

In [ ]:
sqlite> .import Consumer.csv Consumer

# Now we have two tables in our database:

sqlite> .tables
Consumer   TraitInfo

In [ ]:
# These tables are connected by two differents keys: OriginalID
# and FinalID. These are unique IDs for each thermal curve. For each
# FinalID we can get the trait name (OriginalTraitName) from the TraitInfo
# table and the corresponding species name (ConSpecies) from the Consumer table.

sqlite> SELECT A1.FinalID, A1.Consumer, A2.FinalID,  A2.OriginalTraitName
   ...> FROM Consumer A1, TraitInfo A2
   ...> WHERE A1.FinalID=A2.FinalID LIMIT 8;

FinalID     Consumer               FinalID     OriginalTraitName        
----------  ---------------------  ----------  -------------------------
MTD1        Chaoborus trivittatus  MTD1        Resource Consumption Rate
MTD2        Chaoborus trivittatus  MTD2        Resource Consumption Rate
MTD3        Chaoborus americanus   MTD3        Resource Consumption Rate
MTD4        Stizostedion vitreum   MTD4        Resource Mass Consumption
MTD5        Macrobrachium rosenbe  MTD5        Resource Mass Consumption
MTD6        Ranatra dispar         MTD6        Resource Consumption Rate
MTD7        Ceriodaphnia reticula  MTD7        Mass-Specific Mass Consum
MTD8        Polyphemus pediculus   MTD8        Voluntary Body Velocity 

# In the same way we assign alias to variables, we can use them for tables.

This example seems easy because both tables have the same number of
rows. But the query is still as simple when we have tables with
different rows.

In [ ]:
# Let's import the TCP table:

sqlite> CREATE TABLE TCP (Numbers integer primary key,
   ...>                           OriginalID text,
   ...>                           FinalID text,
   ...>                           OriginalTraitValue integer,
   ...>                           OriginalTraitUnit text,
   ...>                           LabGrowthTemp integer,
   ...>                           LabGrowthTempUnit text,   
   ...>                           ConTemp integer,
   ...>                           ConTempUnit text,
   ...>                           ConTempMethod text,
   ...>                           ConAcc text,
   ...>                           ConAccTemp integer);


sqlite> .import TCP.csv TCP
sqlite> .tables
Consumer   TCP        TraitInfo
                          
# Now imagine we want to query the thermal performance curves that we have
# stored for the species Mytilus edulis. Using the FinalID to match the tables,
# the query can be as simple as:

sqlite> SELECT A1.ConTemp, A1.OriginalTraitValue, A2.OriginalTraitName, A3.Consumer
   ...> FROM TCP A1, TraitInfo A2, Consumer A3
   ...> WHERE A1.FinalID=A2.FinalID AND A3.ConSpecies="Mytilus edulis" AND A3.FinalID=A2.FinalID LIMIT 8

ConTemp     OriginalTraitValue    OriginalTraitName               Consumer            
----------  --------------------  ------------------------------  --------------------
25          2.707075              Filtration Rate                 Mytilus edulis      
20          3.40721               Filtration Rate                 Mytilus edulis      
5           3.419455              Filtration Rate                 Mytilus edulis      
15          3.711165              Filtration Rate                 Mytilus edulis      
10          3.875465              Filtration Rate                 Mytilus edulis      
5           0.34                  In Vitro Gill Particle Transpo  Mytilus edulis      
10          0.46                  In Vitro Gill Particle Transpo  Mytilus edulis      
15          0.595                 In Vitro Gill Particle Transpo  Mytilus edulis

So on and so forth (joining tables etc. would come next...). But if you
want to keep practicing and learn more about sqlite commands, this is a
very useful site: <http://www.sqlite.org/sessions/sqlite.html>. You can
store your queries and database management commands in an `
.sql` file (`geany` will take care of syntax
highlighting etc.)

### SQLite with python

It is easy to access, update and manage SQLite databases with `
python` (you should have this script file in your
`Code` directory):

You can create a database in memory, without using the disk — thus you
can create and discard an SQLite database within your workflow!:

## Using Python to build workflows

*This topic will be necessary for your [Miniproject](), which will involve building a reproducible computational workflow.*

You can use python to build an automated data analysis or simulation workflow that involves multiple applications, especially the ones you have already learnt: `R`, LaTeX, & UNIX `bash`.
For example, you could, in theory, write a single Python script to
generate and update your masters dissertation, tables, plots, and all.
Python is ideal for building such workflows because it has packages for
practically every purpose (see Section on Packages above).

### Using `subprocess`

The `subprocess` module is particularly important as it can
run other applications, including R. Let's try – first launch `
ipython`, then `cd` to your python code directory, and
type:

In [ ]:
import subprocess
subprocess.os.system("geany boilerplate.py")
subprocess.os.system("gedit ../Data/TestOaksData.csv")
subprocess.os.system("python boilerplate.py") # A bit silly! 

Easy as pie! You will notice that the terminal remains "connected" to
geany after you run the first of the three lines above, and you have to
quit geany to go on to launcing gedit. To avoid this, you can do:

In [ ]:
subprocess.os.system("geany boilerplate.py &")
subprocess.os.system("gedit ../Data/TestOaksData.csv &")
subprocess.os.system("python boilerplate.py &") # A bit silly! 

Adding a `&` after a program call, i.e., `geany
boilerplate.py &` instead of `geany boilerplate.py`
disconnects the terminal and allows you to run sequential commands in
the terminal/bash.

Similarly, to compile your LaTeXdocument (using `pdflatex` in
this case):

In [ ]:
subprocess.os.system("pdflatex yourlatexdoc.tex")

You can also do this (instead of using `subprocess.os`):

In [ ]:
subprocess.Popen("geany boilerplate.py", shell=True).wait()

You can also use `subprocess.os` to make your code OS (Linux,
Windows, Mac) independent. For example to assign paths:

In [ ]:
subprocess.os.path.join('directory', 'subdirectory', 'file')

The result would be appropriately different on Windows (with backslashes
instead of forward slashes).

Note that in all cases you can "catch" the output of
`subprocess` so that you can then use the output within your
python script. A simple example, where the output is a
platform-dependent directory path, is:

In [ ]:
MyPath = subprocess.os.path.join('directory', 'subdirectory', 'file')

Explore what `subprocess` can do by tabbing
`subprocess.`, and also for submodules, e.g., type
`subprocess.os.` and then tab.

### Running `R`

R is likely an important part of your project's analysis and data
visualization components in particular — for example for statistical
analyses and pretty plotting (Ahem. `ggplot2`).

You can run `R` from Python pretty easily. Try the following:

$\star$

Create an R script file called `TestR.R` in your `
Week6/Code` with the following content:

In [ ]:
print("Hello, this is R!")

Now, create `TestR.py` in
`CMEECourseWork/Week6/Code` with the following content :

In [ ]:
import subprocess
subprocess.Popen("/usr/lib/R/bin/Rscript --verbose TestR.R > \
../Results/TestR.Rout 2> ../Results/TestR_errFile.Rout",\
 shell=True).wait()

`*Note the backslashes*` — this is so that
`python` can read the mutiline script as a single line.

Now run `TestR.py` (or `%cpaste`) and check
`TestR.Rout` and `TestR_errorFile.Rout`.

Also check what happens if you run (type directly in `
ipython` or `python` console):

In [ ]:
subprocess.Popen("/usr/lib/R/bin/Rscript --verbose NonExistScript.R > \
../Results/outputFile.Rout 2> ../Results/errorFile.Rout", \
shell=True).wait()

It is possible that the location of `RScript` is different in
your Ubuntu install. To locate it, try `find /usr -name
'Rscript'` in the linux terminal (not in `python`!).

What do you see on the screen? Now check `outputFile.Rout`
and `errorFile.Rout`.

Practicals
----------

As always, test, add, commit and push all your new code and data to your
git repository.

#### Using `os` problem 1

Open `using_os.py` and complete the tasks assigned\
(hint: you might want to look at `subprocess.os.walk()`)

#### Using `os` problem 2

Open `fmr.R` and work out what it does; check that you have
`NagyEtAl1999.csv`. Now write python code called
`run_fmr_R.py` that:

Runs `fmr.R` to generate the desired result

`run_fmr_R.py` should also print to the python screen
whether the run was successful, and the contents of the R console output

Practicals wrap-up
------------------

1.  Review and make sure you can run all the commands, code fragments,
    and scripts we have till now and get the expected outputs — all
    scripts should work on any other linux laptop.

2.  Include an appropriate docstring (if one is missing) at the
    beginning of `*each*` of each of the python script /
    module files you have written, as well as at the start of every
    function (or sub-module) in a module.

3.  Also annotate your code lines as much and as often as necessary
    using \#.

4.  Keep all files organized in `CMEECourseWork`.

5.  `git add`, `commit` and `push` all
    your week's code and data to your git repository by next Wednesday.

Readings and Resources
----------------------

<http://matplotlib.org/>

For SciPy, the official documentation is great:\
<https://docs.sc.org/doc/scipy/reference/>\
Read about the scipy modules you think will be important to you.

The "ecosystem" for Scientific computing in python:
<http://www.scipy-lectures.org/>

A Primer on Scientific Programming with Python
<http://www.springer.com/us/book/9783642549595>; Multiple copies of this
book are available from the central library and can be requested to
Silwood from the IC library website. You can also find a pdf - google it

Many great examples of applications in the scipy cookbook:
<https://lagunita.stanford.edu/courses/DB/2014/SelfPaced/about>

<https://docs.python.org/2/howto/regex.html>

Google's short class on regex in python:\
<https://developers.google.com/edu/python/regular-expressions>

<http://www.regular-expressions.info/> has a good intro, tips and a
great array of canned solutions

Use and abuse of regex:\
<https://blog.codinghorror.com/regex-use-vs-regex-abuse/>

"The Definitive Guide to SQLite" is a pretty complete guide to SQLite
and freely available from [ 
    http://sd.blackball.lv/library/The_Definitive_Guide_to_SQLite_2nd_edition.pdf]( 
    http://sd.blackball.lv/library/The_Definitive_Guide_to_SQLite_2nd_edition.pdf)

For databses in general, try the Stanford Introduction to Databases
course: <https://www.coursera.org/course/db>