Advanced Biological Computing in Python {#chap:pythonII}
=======================================

In this chapter, we will cover a some topics in Python that will
round-off your python training:

-   Numerical computing in python

-   “Reading” text data using regular expressions in python

-   Databases, and using python to build and manage them

-   Using python to build workflows

<span>*The last topic will be necessary for your Miniproject, which will
involve building a reproducible computational workflow.* </span>

Numerical computing in <span>python</span>
------------------------------------------

The python package <span>scipy</span> can help you do serious number
crunching including,

Linear algebra (matrix and vector operations)

Numerical integration (Solving ODEs)

Fourier transforms

Interpolation

Calculating special functions (incomplete Gamma, Bessel, etc.)

Generation of random numbers

Using statistical functions and transformations

In the following, we will use the <span>array</span> data structure in
<span> scipy</span> for data manipulations and calculations. Scipy
arrays are objects, and are similar in some respects to python lists,
but are more naturally multidimensional, homogeneous in type (the
default is float), and allow efficient (fast) manipulations. Thus scipy
arrays are analogous to the R <span>matrix</span> data object/structure.

The same array objects are accessible within the <span>numpy</span>
package, which is a subset of <span>scipy</span>.

So let’s try <span>scipy</span>:

In [ ]:
In []: import scipy

In []: a = scipy.array(range(5)) # a one-dimensional array

In []: a
Out[]: array([0, 1, 2, 3, 4])

In []: type(a)
Out[]: numpy.ndarray

In []: type(a[0])
Out []: numpy.int64

So all elements in <span>a</span> are of type <span>int</span> because
that is what <span>range()</span> returns (try <span>?range</span>).

![A graphical depiction of numpy/scipy arrays, which can have multiple
dimensions (even greater than 3). From
<http://pages.physics.cornell.edu/~myers/teaching/ComputationalMethods/python/arrays.html>](numpyarray.png){width="100.00000%"}

You can also specify the data type of the array:

In [ ]:
In []: a = scipy.array(range(5), float)

In []: a
Out[]: array([ 0.,  1.,  2.,  3.,  4.])

In []: a.dtype # Check type 
Out[]: dtype('float64')

You can also get a 1-D arrays as follows:

In [ ]:
In []: x = scipy.arange(5)

In []: x
Out[8]: array([0, 1, 2, 3, 4])

In [9]: x = scipy.arange(5.) #directly specify float using decimal

In [10]: x
Out[10]: array([ 0.,  1.,  2.,  3.,  4.])

As with other Python variables (e.g., created as a list or a
dictionary), you can apply methods to variables created as scipy arrays.
For example, TAB after <span>x.</span> to see methods you can apply to
<span>x</span>:

In [ ]:
In [11]: x. 
x.T             x.conj          x.fill          
x.nbytes        x.round         x.take
x.all           x.conjugate     x.flags         
x.ndim          x.searchsorted  x.tofile
x.any           x.copy          x.flat          
x.newbyteorder  x.setfield      x.tolist
x.argmax        x.ctypes        x.flatten       
x.nonzero       x.setflags      x.tostring
x.argmin        x.cumprod       x.getfield      
x.prod          x.shape         x.trace
x.argsort       x.cumsum        x.imag         
x.ptp           x.size          x.transpose
x.astype        x.data          x.item          
x.put           x.sort          x.var
x.base          x.diagonal      x.itemset       
x.ravel         x.squeeze       x.view
x.byteswap      x.dot           x.itemsize      
x.real          x.std           
x.choose        x.dtype         x.max           
x.repeat        x.strides       
x.clip          x.dump          x.mean          
x.reshape       x.sum           
x.compress      x.dumps         x.min           
x.resize        x.swapaxes      

In [12]: x.shape
Out[12]: (5,)

Remember, you can type <span>:?x.methodname</span> to get info on a
particular method. For example, try <span>?x.shape</span>.

You can also convert to and from Python lists:

In [ ]:
In []: b = scipy.array([i for i in range(100) if i%2==1]) #odd numbers 
between 1 and 100

In []: c = b.tolist() #convert back to list
 

To make a matrix, you need a 2-D scipy array:

In [ ]:
In [14]: mat = scipy.array([[0, 1], [2, 3]])

In []: mat.shape
Out[]: (2, 2)

### Indexing and accessing arrays

As with other Python data objects such as lists, scipy array elements
can be accessed using square brackets (\[\]) with the \[row,column\]
reference. Indexing of scipy arrays works like that for other data
strauctures, with index values starting at 0. So, you can obtain all the
elements of a particular row as:

In [ ]:
In []: mat[1] # accessing whole 2nd row, remember indexing starts at 
0
Out[]: array([2, 3])

In [57]: mat[:,1] #accessing whole second column  
Out[57]: array([1, 3])

And accessing particular elements:

In [ ]:
In []: mat[0,0] # 1st row, 1st column element
Out[]: 0
In []: mat[1,0] # 2nd row, 1st column element
Out[]: 2

Note that (like all other programming languages) row index always comes
before column index. That is, <span>mat\[1\]</span> is always going to
mean “whole second row”, and <span>mat\[1,1\]</span> means 1st row and
1st column element. Therefore, to access the whole second column, you
need:

In [ ]:
In []: mat[:,0] #accessing whole first column  
Out[]: array([0, 2])

Python indexing also accepts negative values for going back to the start
from the end of an array:

In [ ]:
In []: mat[0,1]
Out[]: 1

In []: mat[0,-1] #interesting!
Out[]: 1

In []: mat[0,-2] #very interesting, perhaps useless!
Out[]: 0

### Manipulating arrays

Manipulating <span>scipy</span> arrays is pretty straightforward.

A NumPy array is basically described by metadata (number of dimensions,
shape, data type, and so on) and the actual data. The data is stored in
a homogeneous and contiguous block of memory, at a particular address in
system memory (Random Access Memory, or RAM). This block of memory is
called the data buffer. This is the main difference with a pure Python
structure, like a list, where the items are scattered across the system
memory. This aspect is the critical feature that makes NumPy arrays so
efficient.

#### Replacing, adding or deleting elements

Let’s look at how you can replace, add, or delete an array element (a
single entry, or whole row(s) or whole column(s)):

In [ ]:
In []: mat[0,0] = -1 #replace a single element

In []: mat
Out[]: 
array([[-1,  1],
       [ 2,  3]])
       
In []: mat[:,0] = [12,12] #replace whole column

In []: mat
Out[]: 
array([[12,  1],
       [12,  3]])

In []: scipy.append(mat, [[12,12]], axis = 0) #append row, note axis 
specification
Out[]: 
array([[12,  1],
       [12,  3],
       [12, 12]])

In []: scipy.append(mat, [[12],[12]], axis = 1) #append column
Out[]: 
array([[12,  1, 12],
       [12,  3, 12]])

In []: newRow = [[12,12]] #create existing row

In []: mat = scipy.append(mat, newRow, axis = 0) #append that existing row
Out[]: 
array([[12,  1],
       [12,  3],
       [12, 12]])

In []: scipy.delete(mat, 2, 0) #Delete 3rd row
Out[]: 
array([[12,  1],
       [12,  3]])

And concatenation:

In [ ]:
In []: mat = scipy.array([[0, 1], [2, 3]])

In []: mat0 = scipy.array([[0, 10], [-1, 3]])

In []: scipy.concatenate((mat, mat0), axis = 0)
Out[]: 
array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [-1,  3]])

#### Flattening or reshaping arrays

You can also “flatten” or “melt” arrays, that is, change array
dimensions (e.g., from a matrix to a vector):

In [ ]:
In []: mat.ravel()
Out[]: array([0, 1, 2, 3]) # NOTE: ravel is row-priority

In []: mat.reshape((4,1)) # this is different from ravel - check ?scipy.reshape
Out[66]: 
array([[0],
       [1],
       [2],
       [3]])

In []: mat.reshape((1,4)) # NOTE: reshaping is also row-priority
Out[]: array([[0, 1, 2, 3]])

In []: mat.reshape((3, 1)) # But total elements must remain the same!
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-81-ba16cb0744eb> in <module>()
----> 1 mat.reshape((3, 1))

ValueError: total size of new array must be unchanged

This is a bit different than how <span>R</span> behaves (coming up in
Chapters (\[chap:RI\]–\[chap:R\_II\] )), where you won’t get an error
(<span> R</span> “recycles” data), which is more dangerous!

### Pre-allocating arrays

As in other computer languages, it is usually more efficient to
preallocate a array rather than append / insert / concatenate addtional
elelents, rows, or columns. For example, if you know the size of your
matrix or array, you can inititalize it with ones or zeros:

In [ ]:
In []: scipy.ones((4,2)) #(4,2) are the (row,col) array dimensions
Out[]: 
array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In []: scipy.zeros((4,2)) # or zeros
Out[]: 
array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In []: m = scipy.identity(4) #create an identity matrix

In []: m
Out[]: 
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In []: m.fill(16) #fill the matrix with 16

In []: m
Out[26]: 
array([[ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.],
       [ 16.,  16.,  16.,  16.]])

### <span>scipy</span> matrices

Scipy also has a <span>matrix</span> data structure class. Scipy
matrices are strictly 2-Dimensional, while scipy arrays are
N-Dimensional. Matrix objects are a subclass of scipy arrays, so they
inherit all the attributes and methods of scipy arrays (also called
“ndarrays”).

The main advantage of scipy matrices is that they provide a convenient
notation for matrix multiplication: if a and b are matrices, then a\*b
is their matrix product.

#### Matrix-vector operations

Now let’s perform some common matrix-vector operations on arrays (you
also try the same using matrices instead of arrays):

In [ ]:
In []: mm = scipy.arange(16)

In []: mm = mm.reshape(4,4) #Convert to matrix

In []: mm.transpose()
Out[]: 
array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [6]: mm + mm.transpose()
Out[6]: 
array([[ 0,  5, 10, 15],
       [ 5, 10, 15, 20],
       [10, 15, 20, 25],
       [15, 20, 25, 30]])

In [7]: mm - mm.transpose()
Out[7]: 
array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [8]: mm * mm.transpose()
## Elementwise!

Out[8]: 
array([[  0,   4,  16,  36],
       [  4,  25,  54,  91],
       [ 16,  54, 100, 154],
       [ 36,  91, 154, 225]])

In [9]: mm / mm.transpose()
Warning: divide by zero encountered in divide

# Note the integer division
Out[9]: 
array([[0, 0, 0, 0],
       [4, 1, 0, 0],
       [4, 1, 1, 0],
       [4, 1, 1, 1]])

In [10]: mm * scipy.pi
Out[10]: 
array([[  0.      ,   3.14159,   6.28318531,   9.42477796],
       [ 12.566370,  15.70796,  18.84955592,  21.99114858],
       [ 25.132741,  28.27433,  31.41592654,  34.55751919],
       [ 37.699111,  40.84070,  43.98229715,  47.1238898 ]])

In [11]: mm.dot(mm) # MATRIX MULTIPLICATION
Out[11]: 
array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

We can do a lot more (but won’t!) by importing the <span>linalg</span>
sub-package: <span>scipy.linalg</span>.

### Two useful <span>scipy</span> sub-packages

Two particularly useful <span>scipy</span> sub-packages are <span>
scipy.integrate</span> (what will I need this for?) and
<span>scipy.stats</span>. Why not use <span>R</span> for this? — because
often you might just want to calculate some summary stats of your
simulation results within Python.

#### <span>scipy.stats</span>

Let’s take a quick spin in <span>scipy.stats</span>.

In [ ]:
In [18]: import scipy.stats

In [19]: scipy.stats.
scipy.stats.arcsine               scipy.stats.lognorm
scipy.stats.bernoulli             scipy.stats.mannwhitneyu
scipy.stats.beta                  scipy.stats.maxwell
scipy.stats.binom                 scipy.stats.moment
scipy.stats.chi2                  scipy.stats.nanstd
scipy.stats.chisqprob             scipy.stats.nbinom
scipy.stats.circvar               scipy.stats.norm
scipy.stats.expon                 scipy.stats.powerlaw
scipy.stats.gompertz              scipy.stats.t
scipy.stats.kruskal               scipy.stats.uniform

In [19]: scipy.stats.norm.rvs(size = 10) # 10 samples from 
N(0,1)
Out[19]: 
array([-0.951319, -1.997693,  1.518519, -0.975607,  0.8903,
       -0.171347, -0.964987, -0.192849,  1.303369,  0.6728])

In [20]: scipy.stats.norm.rvs(5, size = 10) 
# change mean to 5
Out[20]: 
array([ 6.079362,  4.736106,  3.127175,  5.620740,  5.98831,
        6.657388,  5.899766,  5.754475,  5.353463,  3.24320])

In [21]: scipy.stats.norm.rvs(5, 100, size = 10) 
# change sd to 100
Out[21]: 
array([ -57.886247,   12.620516,  104.654729,  -30.979751,
         41.775710,  -31.423377,  -31.003134,   80.537090,
          3.835486,  103.462095])

# Random integers between 0 and 10
In [23]: scipy.stats.randint.rvs(0, 10, size =7)
Out[23]: array([6, 6, 2, 0, 9, 8, 5])

#### <span>scipy.integrate</span> – the Lotka-Volterra model

Numerical integration is the approximate computation of an integral
using numerical techniques. You need numerical integration whenever you
have a complicated function that cannot be integrated analytically using
anti-derivatives. A common application is solving ordinary differential
equations (ODEs), commonly used for modelling biological systems.

Let’s try <span>scipy.integrate</span> for solving a classical model in
biology — the Lotka-Volterra model for a predator-prey system.

\[$\quad\star$\]

Create <span>LV1.py</span> in your weekly directory and run it.

The Lotka-Volterra model is: $$\label{eqn:LVMod}
\begin{aligned}
    \frac{dR}{dt} &= r R - a C R \\
    \frac{dC}{dt} &= - z C + e a C R
\end{aligned}$$

where $C$ and $R$ are consumer (e.g., predator) and resource (e.g.,
prey) population sizes (either biomass or numbers), $r$ is the intrinsic
growth rate of the resource population, $a$ is a “search rate” that
determines the encounter rate between consumer and resource, $z$ is
mortality rate and $e$ is the consumer’s efficiency in converting
resource to consumer biomass.

<span>LV1.py</span> runs (numerically solves the ODE) this model and
plots the equilbrium. Have good look at the code, line by line, and make
sure that you understand what’s going on. A subsequent practical will
require you to use this code to simulate modified version od the LV
model.

The need for speed: Profiling in Python
---------------------------------------

Donald Knuth says: <span>*Premature optimization is the root of all
evil*</span>. Indeed, computational speed may not be your initial
concern. Also, you should focus on developing clean, reliable, reusable
code rather than worrying first about how fast your code runs. However,
speed will become an issue when and if your analysis or modeling becomes
complex enough (e.g., food web or large network simulations). In that
case, knowing which parts of your code take the most time is useful –
optimizing those parts may save you lots of time. To find out what is
slowing down your code you need to use “profiling”.

### Profiling

Profiling is easy in <span>ipython</span> – simply type the magic
command <span>%run -p your\_function\_name</span>.

Let’s write a simple illustrative program and name it <span>
profileme.py</span>:

Now <span>%run -p profileme.py</span>, and you should see something
like:

In [ ]:
54 function calls in 3.652 seconds

Ordered by: internal time

In [ ]:
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1    2.744    2.744    3.648    3.648 profileme.py:1(a_useless_function)
     2    0.905    0.452    0.905    0.452 {range}
     1    0.002    0.002    0.003    0.003 profileme.py:8(a_less_useless_function)
    [more output]        

The function <span>range</span> is taking long – we should use
<span>xrange</span> instead. When iterating over a large number of
values, <span>xrange</span>, unlike <span>range</span>, does not create
all the values before iteration, but creates them “on demand” (ie.e.,
<span>xrange</span> is a “generator”). Range creates a list, so if you
do <span>range(1, 10000000)</span> it creates a list in memory with
10000000 elements. For example, <span>range(1000000)</span>yields a 4Mb+
list.

So let’s modify the script:

Again running the magic command <span>%run -p</span> yields:

In [ ]:
52 function calls in 2.153 seconds

Ordered by: internal time

In [ ]:
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1    2.150    2.150    2.150    2.150 profileme2.py:1(a_useless_function)
     1    0.002    0.002    0.002    0.002 profileme2.py:8(a_less_useless_function)
     1    0.001    0.001    2.153    2.153 {execfile}
     [more output]

So we saved 1.499 s! (not enough to grab a pint, but ah well...).

### Quick profiling with <span>timeit</span>

Alternatively, if you are writing your script and want to figure out
what the best way to do something (say a particular command or a loop)
might be, then you can use <span>timeit</span>.

Type an run the following code in a python script called <span>
timeitme.py</span>:

Now run it these different instances of timeit-ing by tying the <span>%
timeit</span> command followed by the function call. Note that You can
import all the functions using <span>from timeitme import \*</span>

But remember, don’t go crazy with profiling for the sake of shaving a
couple of milliseconds, tempting as that may be!

Practicals
----------

As always, test, add, commit and push all your new code and data to your
git repository.

#### Lotka-Volterra model problem

Copy and modify <span>LV1.py</span> into another script called
<span>LV2.py</span> that does the following:

1.  Take arguments for the four LV model parameters $ r, a, z ,e$ from
    the commandline

In [ ]:
LV2.py arg1 arg2 ... etc

2.  Runs the Lotka-Volterra model with prey density dependence $r R 
        (1 - \frac{R} {K})$, which changes the coupled ODEs to,
    $$\begin{aligned}
            \frac{dR}{dt} &= r R (1 - \frac{R} {K}) - a C R \\
            \frac{dC}{dt} &= - z C + e a C R
        \end{aligned}$$

3.  Saves the plot as <span>.pdf</span> in an external results directory
    in your weekly directory

4.  The chosen parameter values should show in the plot (e.g.,
    $r = 1, a = .5 $, etc) You can change time length $t$ too.

5.  Include a script in <span>Code</span> that will run both
    <span>LV1.py</span> and <span>LV2.py</span> with
    appropriate arguments. This script should also profile the two
    scripts and print the results to screen for each of the scripts
    using the <span>%run -p</span> approach. Look at and compare the
    speed bottlenecks in <span>LV1.py</span> and <span>LV2.py</span>.
    Think about how you could further speed up the scripts.

<span>*Write every subsequent extra credit script file with a new name
such as <span>LV3.py</span>,<span>LV4.py</span>, etc.* </span>

<span>**Extra credit**</span>: Choose appropriate values for the
parameters such that both predator and prey persist with prey density
dependence — the final (non-zero) population values should be printed to
screen.

<span>**Extra-extra credit**</span>: Write a discrete-time version of
the LV model called <span>LV3.py</span>. The discrete-time model is:
$$\label{eqn:LVDisc} 
    \begin{aligned} 
        R_{t+1} &= R_t (1 + r (1 - \frac{R_t}{K}) - a C_t)\\ 
        C_{t+1} &= C_t (1 - z + e a R_t) 
    \end{aligned}$$ Include this script in <span>run\_LV.py</span>, and
profile it as well.

<span>**Extra-extra-extra credit**</span>: Write a version of the
discrete-time model (eqn \[eqn:LVDisc\]) simulation with a random
gaussian fluctuation in resource’s growth rate at each time-step:
$$\label{eqn:LVFluc1}
    \begin{aligned}
        R_{t+1} &= R_t (1 + (r + \epsilon) (1 - \frac{R_t}{K})- a C_t)\\
        C_{t+1} &= C_t (1 - z + e a R_t)
    \end{aligned}$$ where $\epsilon$ is a random fluctuation drawn from
a gaussian distribution (use <span>scipy.stats</span>). Include this
script in <span> run\_LV.py</span>, and profile it as well.

You can also add fluctuations to both populations simultaneously this
way: $$\label{eqn:LVFluc2}
    \begin{aligned}
        R_{t+1} &= R_t (1 + \epsilon + r +  (1 - \frac{R_t}{K}) - a C_t)\\
        C_{t+1} &= C_t (1 - z + \epsilon + e a R_t)
    \end{aligned}$$

Networks in <span>python</span> (and R)
---------------------------------------

ALL biological systems have a network representation, consisting of
nodes for the biological entities of interest, and edges or links for
the relationships between them. Here are some examples:

Metabolic networks

Gene regulatory networks

Individual-Individual (e.g., social networks)

Food webs

Pollination networks

<span>*Can you think of a few more examples from biology?*</span>

You can easily simulate, analyze, and visualize biological networks in
both <span>python</span> and <span>R</span> using some nifty packages. A
full network anaalysis tutorial is out of the scope of our Python
module’s objectives, but let’s try a simple visualization using the
<span> networkx</span> python package.

For this you need to first install the package:

In [ ]:
$ sudo apt-get install python-networkx  

Now type the code file <span>DrawFW.py</span> and run it:

Look thorugh the code carefully (line-by-line) as there are some new
python objects introduced by <span>networkx</span> for storing node and
edge data.

Practicals
----------

You can also do nice network visualizations in R. Here you will convert
a network visualization script written in <span>R</span> using the
<span> igraph</span> package to a python script that does the same
thing.

First copy the script file called <span>Nets.R</span> and the data files
it calls and run it. This script visualizes the QMEE CDT collaboration
network (see <http://www.imperial.ac.uk/qmee-cdt/>), coloring the the
nodes by the type of node (organization type: “University”,“Hosting
Partner”, “Non-hosting Partner”).

Now, convert this script to a <span>python</span> script that does the
same thing, including writing to an <span>.svg</span> file using the
same QMEE CDT link and node data. You can use <span>networkx</span> or
some other python network visualization package.

Regular expressions in <span>python</span>
------------------------------------------

Let’s shift gears now, and look at a very important skill that you
should learn, or at least be aware of — <span>*Regular
expressions*</span>. Regular expressions (regex) are a tool to find
patterns in strings, such as:

Finding DNA motifs in sequence data

Navigating through files in a directory

Parsing text files

Extracting information from html and xml files

Thus, if you are interested in data mining, need to clean or process
data in any other way, or convert a bunch of information into usable
data, knowing regex is necessary.

\
[www.xkcd.com/208/](www.xkcd.com/208/)

Regex packages are available for most programming languages
(<span>grep</span> in UNIX / Linux, where regex first became popular).

### Metacharacters vs. regular characters

A regex may consist of a combination of “metacharacters” (modifiers) and
“regular” or literal characters. There are 14 metacharacters: <span> \[
\] { } ( ) \\  \^ \$ . $\vert$ ? \* + </span> These metacharacters do
special things, for example:

means match target to <span>1</span> and if that does not match then
match target to <span>2</span>

means match to any character in range <span>0</span> to <span>9</span>

means anything except upper or lower case <span> f</span> and means
everything except lower case <span>a</span> to <span>z</span>

Everything else is interpreted literally (e.g., <span>a</span> is
matched by entering <span>a</span> in the regex).

<span>\[ </span> and <span>\] </span>, specify a character “class” — the
set of characters that you wish to match. Metacharacters are not active
inside classes. For example, will match any of the characters
<span>a</span> to <span>z</span>, but also <span>\$</span>, because
inside a character class it loses its special metacharacter status.

### regex elements

A useful (not exhaustive) list of regex elements is:

  ---------------------------- ----------------------------------------------------------------------------------------------------------------------------------
  <span>a</span>               match the character <span>a</span>
  <span>3</span>               match the number <span>3</span>
  <span>$\backslash$n</span>   match a newline
  <span>$\backslash$t</span>   match a tab
  <span>$\backslash$s</span>   match a whitespace
  <span>.</span>               match any character except line break (newline)
  <span>$\backslash$w</span>   match any alphanumeric character (including underscore)
  <span>$\backslash$W</span>   match any character not covered by <span> $\backslash$w</span> (i.e., match any non-alphanumeric character excluding underscore)
  <span>$\backslash$d</span>   match a numeric character
  <span>$\backslash$D</span>   match any character not covered by <span> $\backslash$d</span> (i.e., match a non-digit)
                               match any character listed: <span>a</span>, <span>t</span>, <span>g</span>, <span>c</span>
  <span>at|gc</span>           match <span>at</span> or <span>gc</span>
                               any character not listed: any character but <span>a</span>, <span>t</span>, <span>g</span>, <span>c</span>
  <span>?</span>               match the preceding pattern element zero or one times
                               match the preceding pattern element zero or more times
  <span>+</span>               match the preceding pattern element one or more times
  <span>{n}</span>             match the preceding pattern element exactly <span>n</span> times
  <span>{n,}</span>            match the preceding pattern element at least <span>n</span> times
  <span>{n,m}</span>           match the preceding pattern element at least <span>n</span> but not more than <span>m</span> times
  <span>\^</span>              match the beginning of a line
  <span>\$</span>              match the end of a line
  ---------------------------- ----------------------------------------------------------------------------------------------------------------------------------

### regex in <span>python</span>

Regex functions in python are in the module <span>re</span> — so we will
<span>import re</span>. The simplest <span>python</span> regex function
is <span> re.search</span>, which searches the string for match to a
given pattern — returns a *match object* if a match is found and
<span>None</span> if not.

<span>**Always**</span> put <span>r</span> in front of your regex — it
tells python to read the regex in its “raw” (literal) form. Without raw
string notation (r“text”), every backslash (’\\’) in a regular
expression would have to be prefixed with another one to escape it.

From <https://docs.python.org/2/library/re.html>: <span>*If you’re not
using a raw string to express the pattern, remember that Python also
uses the backslash as an escape sequence in string literals; if the
escape sequence isn’t recognized by Python’s parser, the backslash and
subsequent character are included in the resulting string. However, if
Python would recognize the resulting sequence, the backslash should be
repeated twice. This is complicated and hard to understand, so it’s
highly recommended that you use raw strings for all but the simplest
expressions.*</span>

OK, let’s try some regexes (type all that follows in <span>
Code/regexs.py</span>):

To know whether a pattern was matched, we can use an <span>if</span>:

In [ ]:
MyStr = 'an example'

match = re.search(r'\w*\s', MyStr)

if match:                      
    print 'found a match:', match.group() 
else:
    print 'did not find a match'    

Here are some more regexes (add all that follows to the
<span>Code/regexs.py</span>):

![In case you were wondering what <span>*Theloderma asper*</span>, the
“bird-shit frog”, looks like. I snapped this one in North-east India
ages ago](thelodermaasper.JPG){width=".5\textwidth"}

You can group regexes into meaningful blocks using parentheses. For
example, let’s try matching a string consisting of an academic’s name,
email address and research area or interest (no need to type this into
any python file):

In [ ]:
MyStr = 'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and 
ecological theory'

# without groups
match = re.search(r"[\w\s]*,\s[\w\.@]*,\s[\w\s&]*",MyStr)

match.group()
'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and ecological theory'

match.group(0)
'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and ecological theory'

# now add groups using ( )
match = re.search(r"([\w\s]*),\s([\w\.@]*),\s([\w\s&]*)",MyStr)

match.group(0)
'Samraat Pawar, s.pawar@imperial.ac.uk, Systems biology and ecological theory'

match.group(1)
'Samraat Pawar'

match.group(2)
's.pawar@imperial.ac.uk'

match.group(3)
'Systems biology and ecological theory'

Have a look at <span>re4.py</span> in your code repository for more on
parsing email addresses using regexes.

### Some RegExercises

These exercises are not for submission as part of your coursework, but
we will discuss them in class (in a later week).

Translate the following regular expressions into regular English (don’t
type this in <span>regexs.py</span>)!

In [ ]:
r'^abc[ab]+\s\t\d'
% 'abca \t1'

r'^\d{1,2}\/\d{1,2}\/\d{4}$'
% '11/12/2004'

r'\s*[a-zA-Z,\s]+\s*'
% ' aBz  '

Write a regex to match dates in format YYYYMMDD, making sure that:

Only seemingly valid dates match (i.e., year greater than 1900)

First digit in month is either 0 or 1

First digit in day $\leq$ 3

### Important <span>re</span> functions

  -------------------------------------- -----------------------------------------------------------------------------------------------------------------------------------------------------------
  <span>re.compile(reg)</span>           Compile a regular expression. In this way the pattern is stored for repeated use, improving the speed.
  <span>re.search(reg, text)</span>      Scan the string and find the first match of the pattern in the string. Returns a <span>match</span> object if successful and <span>None</span> otherwise.
  <span>re.match(reg, text)</span>       as <span>re.search</span>, but only match the beginning of the string.
  <span>re.split(ref, text)</span>       Split the text by the occurrence of the pattern described by the regular expression.
  <span>re.findall(ref, text)</span>     As <span>re.search</span>, but return a list of all the matches. If groups are present, return a list of groups.
  <span>re.finditer(ref, text)</span>    As <span>re.search</span>, but return an iterator containing the next match.
  <span>re.sub(ref, repl, text)</span>   Substitute each non-overlapping occurrence of the match with the text in <span>repl</span> (or a function!).
  -------------------------------------- -----------------------------------------------------------------------------------------------------------------------------------------------------------

Practicals
----------

As always, test, add, commit and push all your new code and data to your
git repository.

#### Blackbirds problem

Complete the code <span>blackbirds.py</span> that you find in the <span>
CMEEMasteRepo</span> (necessary data file is also there).

Databases and <span>python</span>
---------------------------------

Many of you will deal with complex data — and often, lots of it.
Ecological and Evolutionary data are particularly complex because they
contain large numbers of attributes, often measured in very different
scales and units for individual taxa, populations, etc. In this
scenario, storing the data in a database makes a lot of sense! You can
easily include the database in your analysis workflow — indeed, that’s
why people use databases. And you can use python (and R) to build,
manipulate and use your database.

### Relational databases

A <span>*relational*</span> database is a collection of interlinked
(<span> *related*</span>) tables that altogether store a complex dataset
in a logical, computer-readable format. Dividing a dataset into multiple
tables minimizes redundancies. For example, if your data were sampled
from three sites — then, rather than repeating the site name and
description in each row in a text file, you could just specify a
numerical “key” that directs to another table containing the sampling
site name and description.

Finally, if you have many rows in your data file, the type of sequential
access we have been using in our <span>python</span> and <span>R</span>
scripts is inefficient — you should be able to instantly access any row
regardless of its position

Data columns in a database are usually called <span>*fields*</span>,
while the rows are the <span>*records*</span>. Here are a few things to
keep in mind about databases:

Each field typically contains only one data type (e.g., integers,
floats, strings)

Each record is a “data point”, composed of different values, one for
each field — somewhat like a python tuple

Some fields are special, and are called <span>*keys*</span>:

The <span>*primary key*</span> uniquely defines a record in a table
(e.g., each row is identified by a unique number)

To allow fast retrieval, some fields (and typically all the keys) are
indexed — a copy of certain columns that can be searched very
efficiently

<span>*Foreign keys*</span> are keys in a table that are primary keys in
another table and define relationships between the tables

The key to designing a database is to minimize redundancy and dependency
without losing the logical consistency of tables — this is called
<span>*normalization*</span> (arguably more of an art than a science!)

Let’s look at a simple example.

Imagine you recorded body sizes of species from different field sites in
a single text file (e.g., a <span>.csv</span> file) with the following
fields:

  -------------------------------- ---------------------------------------------
  <span>ID</span>                  Unique ID for the record
  <span>SiteName</span>            Name of the site
  <span>SiteLong</span>            Longitude of the site
  <span>SiteLat</span>             Latitude of the site
  <span>SamplingDate</span>        Date of the sample
  <span>SamplingHour</span>        Hour of the sampling
  <span>SamplingAvgTemp</span>     Average air temperature on the sampling day
  <span>SamplingWaterTemp</span>   Temperature of the water
  <span>SamplingPH</span>          PH of the water
  <span>SpeciesCommonName</span>   Species of the sampled individual
  <span>SpeciesLatinBinom</span>   Latin binomial of the species
  <span>BodySize</span>            Width of the individual
  <span>BodyWeight</span>          Weight of the individual
  -------------------------------- ---------------------------------------------

\
It would be logical to divide the data into four tables:

<span>*Site table*</span>:\

  ----------------------- -----------------------
  <span>SiteID</span>     ID for the site
  <span>SiteName</span>   Name of the site
  <span>SiteLong</span>   Longitude of the site
  <span>SiteLat</span>    Latitude of the site
  ----------------------- -----------------------

\
<span>*Sample table*</span>:\

  -------------------------------- --------------------------
  <span>SamplingID</span>          ID for the sampling date
  <span>SamplingDate</span>        Date of the sample
  <span>SamplingHour</span>        Hour of the sample
  <span>SamplingAvgTemp</span>     Average air temperature
  <span>SamplingWaterTemp</span>   Temperature of the water
  <span>SamplingPH</span>          PH of the water
  -------------------------------- --------------------------

\
<span>*Species table*</span>:\

  -------------------------------- -------------------------------
  <span>SpeciesID</span>           ID for the species
  <span>SpeciesCommonName</span>   Species name
  <span>SpeciesLatinBinom</span>   Latin binomial of the species
  -------------------------------- -------------------------------

\
<span>*Individual table*</span>:\

  --------------------------- -------------------------------
  <span>IndividualID</span>   ID for the individual sampled
  <span>SpeciesID</span>      ID for the species
  <span>SamplingID</span>     ID for the sampling day
  <span>SiteID</span>         ID for the site
  <span>BodySize</span>       Width of the individual
  <span>BodyWeight</span>     Weight of the individual
  --------------------------- -------------------------------

\
In each table, the first ID field is the primary key. The last table
contains three foreign keys because each individual is associated with
one species, one sampling day and one sampling site.

These structural features of a database are called its
<span>*schema*</span>.

### SQLite

<span>SQLite</span> is a simple (and very popular) SQL (Structured Query
Language)-based solution for managing localized, personal databases. I
can safely bet that most, if not all of you unknowingly (or knowingly!)
use <span>SQLite</span> — it is used by MacOSX, Firefox, Acrobat Reader,
iTunes, Skype, iPhone, etc. SQLite is also the database “engine”
underlying your Siwlood Masters Web App: <http://silwoodmasters.co.uk>

We can easily use SQLite through Python scripts. First, install SQLite
by typing in the Ubuntu terminal:

In [ ]:
$ sudo apt-get install sqlite3 libsqlite3-dev

Also, make sure that you have the necessary package for python by typing
<span>import sqlite3</span> in the python or ipython shell. Finally, you
may install a GUI for SQLite3 :

In [ ]:
$ sudo apt-get install sqliteman

Now type <span>sqlite3</span> in the Ubuntu terminal to check if SQLite
successfully launches.

SQLite has very few data types (and lacks a boolean and a date type):

  ---------------------- ----------------------------------------------------------------------------------------------------------------------
  <span>NULL</span>      The value is a NULL value
  <span>INTEGER</span>   The value is a signed integer, stored in up to or 8 bytes
  <span>REAL</span>      The value is a floating point value, stored as in 8 bytes
  <span>TEXT</span>      The value is a text string
  <span>BLOB</span>      The value is a blob of data, stored exactly as it was input (useful for binary types, such as bitmap images or pdfs)
  ---------------------- ----------------------------------------------------------------------------------------------------------------------

\
Typically, you will build a database by importing csv data — be aware
that:

Headers: the csv should have no headers

Separators: if the comma is the separator, each record should not
contain any other commas

Quotes: there should be no quotes in the data

Newlines: there should be no newlines

Now build your first database in SQLite! We will use as example a global
dataset on metabolic traits called <span>*Biotraits*</span> that we are
currently developing in our lab (should be in your <span>Data</span>
directory). This dataset contains 164 columns (fields). Thermal response
curves for different traits and species are stored in rows. This means
that site description or taxonomy are repeated as many times as
temperatures are measured in the curve. You can imagine how much
redundacy can be here!!!

For this reason, it is easier to migrate the dataset to SQL and split it
into several tables:

TCP: Includes the thermal curve performance for each species and trait
(as many rows per trait and species as temperatures have been measured
within the TCP)

TraitInfo: Contains site description and conditions under the traits
were measured (one row per thermal curve)

Consumer: Consumer description including taxonomy (one row per thermal
curve).

Resource: Resource description including taxonomy (one row per thermal
curve).

Size: Size data for each species (one row per thermal curve)

DataSource: Contains information about the data source (citation,
contributors) (one row per thermal curve).

So all these tables compose the <span>*Biotraits*</span>
<span>schema</span>.

Navigate to your <span>Data</span> directory and in an Ubuntu terminal
type:

In [ ]:
$ sqlite3 Biotraits.db
SQLite version 3.7.9
Enter ".help" for instructions
Enter SQL statements terminated with a ";"

This creates an empty database in your <span>Data</span> directory. Now,
you need to create a table with some fields. Let’s start with the
<span>*TraitInfo*</span> table:

In [ ]:
sqlite> CREATE TABLE TraitInfo (Numbers integer primary key,
   ...>                                 OriginalID text,
   ...>                                 FinalID text,
   ...>                                 OriginalTraitName text,
   ...>                                 OriginalTraitDef text,
   ...>                                 Replicates integer,
   ...>                                 Habitat  integer,               
   ...>                                 Climate text,
   ...>                                 Location text,
   ...>                                 LocationType text,
   ...>                                 LocationDate text,
   ...>                                 CoordinateType text,
   ...>                                 Latitude integer,
   ...>                                 Longitude integer);

Note that I am writing all SQL commands in upper case, but it is not
necessary. I am using upper case here because SQL syntax is long and
clunky, and it quickly becomes hard to spot (and edit) commands in long
strings of complex queries.

Now let’s import the dataset:

In [ ]:
sqlite> .mode csv

sqlite> .import TraitInfo.csv TraitInfo

So we built a table and imported a csv file into it. Now we can ask
SQLite to show all the tables we currently have:

In [ ]:
sqlite> .tables

TraitInfo

Let’s run our first <span>*Query*</span> (note that you need a semicolon
to end a command):

In [ ]:
sqlite> SELECT * FROM TraitInfo LIMIT 5;

1,1,MTD1,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
2,1,MTD1,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
3,1,MTD1,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
4,2,MTD2,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323
5,2,MTD2,"Resource Consumption Rate","The number of resource consumed per number of consumers per time",6,freshwater,temperate,"Eunice Lake; Ontario; Canada",NA,NA,NA,51.254,-85.323

Let’s turn on some nicer formatting:

In [ ]:
sqlite> .mode column

sqlite> .header ON

sqlite> SELECT * FROM TraitInfo LIMIT 5;

Numbers  OriginalID  FinalID     OriginalTraitName           ... 
-------  ----------  ----------  -------------------------   ...
1        1           MTD1        Resource Consumption Rate   ...
4        2           MTD2        Resource Consumption Rate   ...
6        3           MTD3        Resource Consumption Rate   ...
9        4           MTD4        Resource Mass Consumption   ...
12       5           MTD5        Resource Mass Consumption   ...

The main statement to select records from a table is
<span>SELECT</span>:

In [ ]:
sqlite> .width 40  ## NOTE: Control the width

sqlite> SELECT DISTINCT OriginalTraitName FROM TraitInfo; # Returns unique values

OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Mass-Specific Mass Consumption Rate     
Voluntary Body Velocity                 
Forward Attack Distance                 
Foraging Velocity                       
Resource Reaction Distance                   
....

sqlite> SELECT DISTINCT Habitat FROM TraitInfo
   ...> WHERE OriginalTraitName = "Resource Consumption Rate"; # Sets a condition

Habitat                                 
----------------------------------------
freshwater                              
marine                                  
terrestrial 

sqlite> SELECT COUNT (*) FROM TraitInfo;  # Returns number of rows

Count (*)           
--------------------
2336

sqlite> SELECT Habitat, COUNT(OriginalTraitName) # Returns number of rows for each group
   ...> FROM TraitInfo GROUP BY Habitat;

Habitat     COUNT(OriginalTraitName)
----------  ------------------------
NA          16                      
freshwater  609                     
marine      909                     
terrestria  802   

sqlite> SELECT COUNT(DISTINCT OriginalTraitName) # Returns number of unique values
   ...> FROM TraitInfo;

COUNT(DISTINCT OriginalTraitName)
---------------------------------
220   

sqlite> SELECT COUNT(DISTINCT OriginalTraitName) TraitCount # Assigns alias to the variable
   ...> FROM TraitInfo;

TraitCount
----------
220 

sqlite> SELECT Habitat,
   ...> COUNT(DISTINCT OriginalTraitName) AS TN
   ...> FROM TraitInfo GROUP BY Habitat;

Habitat     TN        
----------  ----------
NA          7         
freshwater  82        
marine      95        
terrestria  96     


sqlite> SELECT * # WHAT TO SELECT
   ...> FROM TraitInfo # FROM WHERE
   ...> WHERE Habitat = "marine" # CONDITIONS
   ...> AND OriginalTraitName = "Resource Consumption Rate";

Numbers     OriginalID  FinalID     OriginalTraitName          ...
----------  ----------  ----------  -------------------------  ...
778         308         MTD99       Resource Consumption Rate  ...
798         310         MTD101      Resource Consumption Rate  ...
806         311         MTD102      Resource Consumption Rate  ...
993         351         MTD113      Resource Consumption Rate  ...

The structure of the <span>SELECT</span> commend is as follows
(<span>*Note: <span>**all**</span> characters are case
<span>**in**</span>sensitive*</span>):

In [ ]:
SELECT [DISTINCT] field
FROM table
WHERE predicate
GROUP BY field
HAVING predicate
ORDER BY field
LIMIT number
;

Let’s try some more elaborate queries:

In [ ]:
sqlite> SELECT Numbers FROM TraitInfo LIMIT 5;

Numbers   
----------
1         
4         
6         
9         
12      

sqlite> SELECT Numbers 
   ...> FROM TraitInfo
   ...> WHERE Numbers > 100 
   ...> AND Numbers < 200;

Numbers   
----------
107       
110       
112       
115         

sqlite> SELECT Numbers 
   ...> FROM TraitInfo
   ...> WHERE Habitat = "freshwater"
   ...> AND Number > 700
   ...> AND Number < 800;

Numbers   
----------
704       
708       
712       
716       
720       
725       
730       
735       
740       
744       
748       
      

You can also match records using something like regular expressions. In
SQL, when we use the command <span>LIKE</span>, the percent % symbol
matches any sequence of zero or more characters and the underscore
matches any single character. Similarly, <span>GLOB</span> uses the
asterisk and the underscore.

In [ ]:
sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName LIKE "_esource Consumption Rate";

OriginalTraitName        
-------------------------
Resource Consumption Rate          

sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName LIKE "Resource%";

OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Resource Reaction Distance              
Resource Habitat Encounter Rate         
Resource Consumption Probability        
Resource Mobility Selection             
Resource Size Selection                 
Resource Size Capture Intent Acceptance 
Resource Encounter Rate                 
Resource Escape Response Probability 

sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName GLOB "Resource*";


OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Resource Reaction Distance              
Resource Habitat Encounter Rate         
Resource Consumption Probability        
Resource Mobility Selection             
Resource Size Selection                 
Resource Size Capture Intent Acceptance 
Resource Encounter Rate                 
Resource Escape Response Probability 

# NOTE THAT GLOB IS CASE SENSITIVE, WHILE LIKE IS NOT

sqlite> SELECT DISTINCT OriginalTraitName
   ...> FROM TraitInfo
   ...> WHERE OriginalTraitName LIKE "resource%";

OriginalTraitName                       
----------------------------------------
Resource Consumption Rate               
Resource Mass Consumption Rate          
Resource Reaction Distance              
Resource Habitat Encounter Rate         
Resource Consumption Probability        
Resource Mobility Selection             
Resource Size Selection                 
Resource Size Capture Intent Acceptance 
Resource Encounter Rate                 
Resource Escape Response Probability 

We can also order by any column:

In [ ]:
sqlite> SELECT OriginalTraitName, Habitat FROM 
   ...>  TraitInfo LIMIT 5;

OriginalTraitName          Habitat   
-------------------------  ----------
Resource Consumption Rate  freshwater
Resource Consumption Rate  freshwater
Resource Consumption Rate  freshwater
Resource Mass Consumption  freshwater
Resource Mass Consumption  freshwater

sqlite> SELECT OriginalTraitName, Habitat FROM 
   ...> TraitInfo ORDER BY OriginalTraitName LIMIT 5;

OriginalTraitName           Habitat   
--------------------------  ----------
48-hr Hatching Probability  marine    
Asexual Reproduction Rate   marine    
Attack Body Acceleration    marine    
Attack Body Velocity        marine    
Attack Body Velocity        marine  
 

Until now we have just queried data from one single table, but as we
have seen, the point of storing a database in SQL is that we can use
multiple tables minimizing redundancies within them. And of course,
querying data from those different tables at the same time will be
necessary at some point.

Let’s import then one more table to our database:

In [ ]:
sqlite> CREATE TABLE Consumer (Numbers integer primary key,
  ...>                                OriginalID text,
  ...>                                FinalID text,
  ...>                                Consumer text,
  ...>                                ConCommon text,
  ...>                                ConKingdom text,
  ...>                                ConPhylum text,
  ...>                                ConClass text,
  ...>                                ConOrder text,
  ...>                                ConFamily text,
  ...>                                ConGenus text,
  ...>                                ConSpecies text);

In [ ]:
sqlite> .import Consumer.csv Consumer

# Now we have two tables in our database:

sqlite> .tables
Consumer   TraitInfo

In [ ]:
# These tables are connected by two differents keys: OriginalID
# and FinalID. These are unique IDs for each thermal curve. For each
# FinalID we can get the trait name (OriginalTraitName) from the TraitInfo
# table and the corresponding species name (ConSpecies) from the Consumer table.

sqlite> SELECT A1.FinalID, A1.Consumer, A2.FinalID,  A2.OriginalTraitName
   ...> FROM Consumer A1, TraitInfo A2
   ...> WHERE A1.FinalID=A2.FinalID LIMIT 8;

FinalID     Consumer               FinalID     OriginalTraitName        
----------  ---------------------  ----------  -------------------------
MTD1        Chaoborus trivittatus  MTD1        Resource Consumption Rate
MTD2        Chaoborus trivittatus  MTD2        Resource Consumption Rate
MTD3        Chaoborus americanus   MTD3        Resource Consumption Rate
MTD4        Stizostedion vitreum   MTD4        Resource Mass Consumption
MTD5        Macrobrachium rosenbe  MTD5        Resource Mass Consumption
MTD6        Ranatra dispar         MTD6        Resource Consumption Rate
MTD7        Ceriodaphnia reticula  MTD7        Mass-Specific Mass Consum
MTD8        Polyphemus pediculus   MTD8        Voluntary Body Velocity 

# In the same way we assign alias to variables, we can use them for tables.

This example seems easy because both tables have the same number of
rows. But the query is still as simple when we have tables with
different rows.

In [ ]:
# Let's import the TCP table:

sqlite> CREATE TABLE TCP (Numbers integer primary key,
   ...>                           OriginalID text,
   ...>                           FinalID text,
   ...>                           OriginalTraitValue integer,
   ...>                           OriginalTraitUnit text,
   ...>                           LabGrowthTemp integer,
   ...>                           LabGrowthTempUnit text,   
   ...>                           ConTemp integer,
   ...>                           ConTempUnit text,
   ...>                           ConTempMethod text,
   ...>                           ConAcc text,
   ...>                           ConAccTemp integer);


sqlite> .import TCP.csv TCP
sqlite> .tables
Consumer   TCP        TraitInfo
                          
# Now imagine we want to query the thermal performance curves that we have
# stored for the species Mytilus edulis. Using the FinalID to match the tables,
# the query can be as simple as:

sqlite> SELECT A1.ConTemp, A1.OriginalTraitValue, A2.OriginalTraitName, A3.Consumer
   ...> FROM TCP A1, TraitInfo A2, Consumer A3
   ...> WHERE A1.FinalID=A2.FinalID AND A3.ConSpecies="Mytilus edulis" AND A3.FinalID=A2.FinalID LIMIT 8

ConTemp     OriginalTraitValue    OriginalTraitName               Consumer            
----------  --------------------  ------------------------------  --------------------
25          2.707075              Filtration Rate                 Mytilus edulis      
20          3.40721               Filtration Rate                 Mytilus edulis      
5           3.419455              Filtration Rate                 Mytilus edulis      
15          3.711165              Filtration Rate                 Mytilus edulis      
10          3.875465              Filtration Rate                 Mytilus edulis      
5           0.34                  In Vitro Gill Particle Transpo  Mytilus edulis      
10          0.46                  In Vitro Gill Particle Transpo  Mytilus edulis      
15          0.595                 In Vitro Gill Particle Transpo  Mytilus edulis

So on and so forth (joining tables etc. would come next...). But if you
want to keep practicing and learn more about sqlite commands, this is a
very useful site: <http://www.sqlite.org/sessions/sqlite.html>. You can
store your queries and database management commands in an <span>
.sql</span> file (<span>geany</span> will take care of syntax
highlighting etc.)

### SQLite with python

It is easy to access, update and manage SQLite databases with <span>
python</span> (you should have this script file in your
<span>Code</span> directory):

You can create a database in memory, without using the disk — thus you
can create and discard an SQLite database within your workflow!:

Using <span>python</span> to build workflows
--------------------------------------------

You can use python to build an automated data analysis or simulation
workflow that involves multiple applications, especially the ones you
have already learnt: <span>R</span>, LaTeX, & UNIX <span>bash</span>.
For example, you could, in theory, write a single Python script to
generate and update your masters dissertation, tables, plots, and all.
Python is ideal for building such workflows because it has packages for
practically every purpose (see Section on Packages above).

### Using <span>subprocess</span>

The <span>subprocess</span> module is particularly important as it can
run other applications, including R. Let’s try – first launch <span>
ipython</span>, then <span>cd</span> to your python code directory, and
type:

In [ ]:
import subprocess
subprocess.os.system("geany boilerplate.py")
subprocess.os.system("gedit ../Data/TestOaksData.csv")
subprocess.os.system("python boilerplate.py") # A bit silly! 

Easy as pie! You will notice that the terminal remains “connected” to
geany after you run the first of the three lines above, and you have to
quit geany to go on to launcing gedit. To avoid this, you can do:

In [ ]:
subprocess.os.system("geany boilerplate.py &")
subprocess.os.system("gedit ../Data/TestOaksData.csv &")
subprocess.os.system("python boilerplate.py &") # A bit silly! 

Adding a <span>&</span> after a program call, i.e., <span>geany
boilerplate.py &</span> instead of <span>geany boilerplate.py</span>
disconnects the terminal and allows you to run sequential commands in
the terminal/bash.

Similarly, to compile your LaTeXdocument (using <span>pdflatex</span> in
this case):

In [ ]:
subprocess.os.system("pdflatex yourlatexdoc.tex")

You can also do this (instead of using <span>subprocess.os</span>):

In [ ]:
subprocess.Popen("geany boilerplate.py", shell=True).wait()

You can also use <span>subprocess.os</span> to make your code OS (Linux,
Windows, Mac) independent. For example to assign paths:

In [ ]:
subprocess.os.path.join('directory', 'subdirectory', 'file')

The result would be appropriately different on Windows (with backslashes
instead of forward slashes).

Note that in all cases you can “catch” the output of
<span>subprocess</span> so that you can then use the output within your
python script. A simple example, where the output is a
platform-dependent directory path, is:

In [ ]:
MyPath = subprocess.os.path.join('directory', 'subdirectory', 'file')

Explore what <span>subprocess</span> can do by tabbing
<span>subprocess.</span>, and also for submodules, e.g., type
<span>subprocess.os.</span> and then tab.

### Running <span>R</span>

R is likely an important part of your project’s analysis and data
visualization components in particular — for example for statistical
analyses and pretty plotting (Ahem. <span>ggplot2</span>).

You can run <span>R</span> from Python pretty easily. Try the following:

\[$\quad\star$\]

Create an R script file called <span>TestR.R</span> in your <span>
Week6/Code</span> with the following content:

In [ ]:
print("Hello, this is R!")

Now, create <span>TestR.py</span> in
<span>CMEECourseWork/Week6/Code</span> with the following content :

In [ ]:
import subprocess
subprocess.Popen("/usr/lib/R/bin/Rscript --verbose TestR.R > \
../Results/TestR.Rout 2> ../Results/TestR_errFile.Rout",\
 shell=True).wait()

<span>*Note the backslashes*</span> — this is so that
<span>python</span> can read the mutiline script as a single line.

Now run <span>TestR.py</span> (or <span>%cpaste</span>) and check
<span>TestR.Rout</span> and <span>TestR\_errorFile.Rout</span>.

Also check what happens if you run (type directly in <span>
ipython</span> or <span>python</span> console):

In [ ]:
subprocess.Popen("/usr/lib/R/bin/Rscript --verbose NonExistScript.R > \
../Results/outputFile.Rout 2> ../Results/errorFile.Rout", \
shell=True).wait()

It is possible that the location of <span>RScript</span> is different in
your Ubuntu install. To locate it, try <span>find /usr -name
’Rscript’</span> in the linux terminal (not in <span>python</span>!).

What do you see on the screen? Now check <span>outputFile.Rout</span>
and <span>errorFile.Rout</span>.

Practicals
----------

As always, test, add, commit and push all your new code and data to your
git repository.

#### Using <span>os</span> problem 1

Open <span>using\_os.py</span> and complete the tasks assigned\
(hint: you might want to look at <span>subprocess.os.walk()</span>)

#### Using <span>os</span> problem 2

Open <span>fmr.R</span> and work out what it does; check that you have
<span>NagyEtAl1999.csv</span>. Now write python code called
<span>run\_fmr\_R.py</span> that:

Runs <span>fmr.R</span> to generate the desired result

<span>run\_fmr\_R.py</span> should also print to the python screen
whether the run was successful, and the contents of the R console output

Practicals wrap-up
------------------

1.  Review and make sure you can run all the commands, code fragments,
    and scripts we have till now and get the expected outputs — all
    scripts should work on any other linux laptop.

2.  Include an appropriate docstring (if one is missing) at the
    beginning of <span>*each*</span> of each of the python script /
    module files you have written, as well as at the start of every
    function (or sub-module) in a module.

3.  Also annotate your code lines as much and as often as necessary
    using \#.

4.  Keep all files organized in <span>CMEECourseWork</span>.

5.  <span>git add</span>, <span>commit</span> and <span>push</span> all
    your week’s code and data to your git repository by next Wednesday.

Readings and Resources
----------------------

<http://matplotlib.org/>

For SciPy, the official documentation is great:\
<https://docs.scipy.org/doc/scipy/reference/>\
Read about the scipy modules you think will be important to you.

The “ecosystem” for Scientific computing in python:
<http://www.scipy-lectures.org/>

A Primer on Scientific Programming with Python
<http://www.springer.com/us/book/9783642549595>; Multiple copies of this
book are available from the central library and can be requested to
Silwood from the IC library website. You can also find a pdf - google it

Many great examples of applications in the scipy cookbook:
<https://lagunita.stanford.edu/courses/DB/2014/SelfPaced/about>

<https://docs.python.org/2/howto/regex.html>

Google’s short class on regex in python:\
<https://developers.google.com/edu/python/regular-expressions>

<http://www.regular-expressions.info/> has a good intro, tips and a
great array of canned solutions

Use and abuse of regex:\
<https://blog.codinghorror.com/regex-use-vs-regex-abuse/>

“The Definitive Guide to SQLite” is a pretty complete guide to SQLite
and freely available from [ 
    http://sd.blackball.lv/library/The\_Definitive\_Guide\_to\_SQLite\_2nd\_edition.pdf]( 
    http://sd.blackball.lv/library/The_Definitive_Guide_to_SQLite_2nd_edition.pdf)

For databses in general, try the Stanford Introduction to Databases
course: <https://www.coursera.org/course/db>